Repository ovh-ux/ovh-manager-telecom, pull requests merged in 2018-09, with the labels that each got.

#857 fix(xdsl): patch diagnostic module
  package.json
  yarn.lock
Labels: bug, quality check ok

#859 fix(sms.senders.add): apply tag-pair rule on tbody elements
  client/app/telecom/sms/senders/add/telecom-sms-senders-add.html
Labels: bug

#853 fix(telephony order): translations broken for typology
  client/app/telecom/telephony/billingAccount/orderAlias/special/telecom-telephony-billing-account-orderAlias-special.controller.js
  client/app/telecom/telephony/billingAccount/orderAlias/special/telecom-telephony-billing-account-orderAlias-special.js
Labels: bug, quality check ok

#869 chore(webpack): fix slots ng-include
  client/app/telecom/freeFax/freeFax.js
  client/app/telecom/overTheBox/details/overTheBox-details.js
  client/app/telecom/overTheBox/order/order-overTheBox.js
  client/app/telecom/pack/pack.js
  client/app/telecom/pack/xdsl/pack-xdsl.js
  client/app/telecom/telephony/line/assist/troubleshooting/telecom-telephony-line-assist-troubleshooting.js
Labels: bug

#868 chore(deps): fix jquery.scrollTo dep, add popper.js
  client/app/index.js
  package.json
  yarn.lock
Labels: bug

#870 chore(webpack): fix async loader
  client/app/app.js
  client/app/async-loader.factory.js
Labels: bug

#872 fix(ui-router): remove missing state translations
  client/app/telecom/freeFax/voicemailConfiguration/freeFax-voicemailConfiguration.js
  client/app/telecom/pack/move/pack-move.js
  client/app/telecom/pack/resiliation/pack-resiliation.js
  client/app/telecom/pack/slots/emailPro/detail/pack-emailPro-detail.js
  client/app/telecom/pack/slots/hostedEmail/detail/pack-hostedEmail-detail.js
  client/app/telecom/pack/slots/voipLine/activation/pack-voipLine-activation.js
  client/app/telecom/pack/xdsl/access/ip/pack-xdsl-access-ip.js
  client/app/telecom/pack/xdsl/access/linediagnostic/pack-xdsl-access-linediagnostic.js
  client/app/telecom/pack/xdsl/access/notifications/pack-xdsl-access-notifications.js
  client/app/telecom/pack/xdsl/missingRio/pack-xdsl-missing-rio.js
  client/app/telecom/pack/xdsl/pack-xdsl.js
  client/app/telecom/pack/xdsl/resiliation/pack-xdsl-resiliation.js
  client/app/telecom/telephony/alias/configuration/timeCondition/easyHunting/telecom-telephony-alias-configuration-time-condition-easy-hunting.js
  client/app/telecom/telephony/alias/configuration/timeCondition/oldPabx/telecom-telephony-alias-configuration-time-condition-old-pabx.js
  client/app/telecom/telephony/billingAccount/abbreviatedNumbers/telecom-telephony-abbreviatedNumbers.js
  client/app/telecom/telephony/billingAccount/administration/telecom-telephony-billing-account-administration.js
  client/app/telecom/telephony/line/calls/abbreviatedNumbers/telecom-telephony-line-calls-abbreviatedNumbers.js
  client/app/telecom/telephony/line/calls/click2Call/add-user/telecom-telephony-line-calls-click2Call-add-user.js
  client/app/telecom/telephony/line/calls/click2Call/change-password/telecom-telephony-line-calls-click2Call-change-password-user.js
  client/app/telecom/telephony/line/calls/timeCondition/telecom-telephony-line-calls-time-condition.js
  client/app/telecom/telephony/line/management/password/telecom-telephony-line-management-password.js
  client/app/telecom/telephony/telecom-telephony.js
Labels: bug

#875 chore(webpack): import telecom components translations
  client/components/elapsed-time/elapsed-time.directive.js
  client/components/notification/notification.component.js
  client/components/ovh-task-follow/ovh-task-follow.component.js
  client/components/resiliation/resiliation-reason.component.js
  client/components/shippingModeSelection/shipping-mode-selection.component.js
  client/components/sidebar/sidebar.config.js
  client/components/telecom/alias/hunting/sounds/telecom-telephony-alias-hunting-sounds.controller.js
  client/components/telecom/retractation/telecom-retractation.component.js
  client/components/telecom/telephony/abbreviatedNumbers/telecom-telephony-abbreviated-numbers.component.js
  client/components/telecom/telephony/alias/liveCalls/telecom-telephony-alias-configuration-liveCalls.component.js
  client/components/telecom/telephony/alias/members/telecom-telephony-alias-members.component.js
  client/components/telecom/telephony/alias/records/telecom-telephony-alias-records.component.js
  client/components/telecom/telephony/alias/svaGenerator/telephony-alias-svaGenerator.directive.js
  client/components/telecom/telephony/associateDevice/telecom-telephony-associate-device.component.js
  client/components/telecom/telephony/bulkAction/telephony-bulk-action.component.js
  client/components/telecom/telephony/callsFiltering/telecom-telephony-callsFilteringAdd.component.js
  client/components/telecom/telephony/group/consumption/pie-chart/telephony-group-consumption-pie-chart.directive.js
  client/components/telecom/telephony/group/number/feature/conference/telephony-group-number-feature-conference.component.js
  client/components/telecom/telephony/group/number/feature/ovhPabx/menu/list/telephony-group-number-feature-ovh-pabx-menu-list.component.js
  client/components/telecom/telephony/group/number/feature/ovhPabx/menu/telephony-group-number-feature-ovh-pabx-menu.component.js
  client/components/telecom/telephony/group/number/feature/ovhPabx/sound/list/telephony-group-number-feature-ovh-pabx-sound-list.component.js
  client/components/telecom/telephony/group/number/feature/ovhPabx/sound/popover-section/telephony-group-number-feature-ovh-pabx-sound-popover-section.component.js
  client/components/telecom/telephony/group/number/feature/ovhPabx/telephony-group-number-feature-ovh-pabx.component.js
  client/components/telecom/telephony/group/number/feature/ovhPabx/tts/create/telephony-group-number-feature-ovh-pabx-tts-create.component.js
  client/components/telecom/telephony/group/number/feature/ovhPabx/tts/telephony-group-number-feature-ovh-pabx-tts.factory.js
  client/components/telecom/telephony/group/number/telephony-group-number.component.js
  client/components/telecom/telephony/scheduler/telephony-scheduler.directive.js
  client/components/telecom/telephony/service/choice-popover/telecom-telephony-service-choice-popover.directive.js
  client/components/telecom/telephony/timeCondition/condition/telephony-time-condition-condition.factory.js
  client/components/telecom/telephony/timeCondition/slot/telephony-time-condition-slot.component.js
Labels: bug

#876 chore(webpack): fix line calls blank screen
  client/app/telecom/telephony/line/calls/telecom-telephony-line-calls.html
Labels: bug

#879 Fix/mondial relay
  client/app/app.less
  client/app/telecom/telephony/fax/fax/customDomains/telecom-telephony-fax-fax-customDomains.js
  client/app/telecom/telephony/fax/fax/password/telecom-telephony-fax-fax-password.js
  client/app/telecom/telephony/line/consumption/telecom-telephony-line-consumption.js
  client/app/telecom/telephony/line/fax/customDomains/telecom-telephony-line-fax-customDomains.js
  client/app/telecom/telephony/line/fax/password/telecom-telephony-line-fax-password.js
  client/components/ovh-angular-mondial-relay/ovh-angular-mondial-relay.js
Labels: bug

#878 fix(trads): fix consumptions & fax translations
  client/app/telecom/telephony/fax/fax/customDomains/telecom-telephony-fax-fax-customDomains.js
  client/app/telecom/telephony/fax/fax/password/telecom-telephony-fax-fax-password.js
  client/app/telecom/telephony/line/consumption/telecom-telephony-line-consumption.js
  client/app/telecom/telephony/line/fax/customDomains/telecom-telephony-line-fax-customDomains.js
  client/app/telecom/telephony/line/fax/password/telecom-telephony-line-fax-password.js
Labels: bug

#880 chore(webpack): import sidebar translations
  client/components/sidebar/sidebar.js
Labels: bug

#881 chore(webpack): import missing components css
  client/app/app.less
Labels: bug

#884 chore(webpack): import ovh-angular-timeline less
  client/app/app.less
Labels: bug

#885 fix(oui-action-menu-item): replace deprecated text attribute
  client/components/telecom/telephony/abbreviatedNumbers/telecom-telephony-abbreviated-numbers.html
  client/components/telecom/telephony/alias/liveCalls/telecom-telephony-alias-configuration-liveCalls.html
Labels: bug

#886 chore(webpack): fix angular-flash less import
  client/app/app.less
Labels: bug

#887 chore(webpack): fix assist trads
  client/app/telecom/telephony/fax/assist/telecom-telephony-fax-assist.js
  client/app/telecom/telephony/fax/consumption/incomingFax/telecom-telephony-fax-consumption-incomingFax.js
  client/app/telecom/telephony/fax/consumption/outgoingFax/telecom-telephony-fax-consumption-outgoingFax.js
  client/app/telecom/telephony/line/assist/logs/telecom-telephony-line-assist-logs.js
  client/app/telecom/telephony/line/assist/telecom-telephony-line-assist.js
Labels: bug

#889 chore(webpack): fix missing trad
  client/app/telecom/telephony/alias/configuration/mode/easyHunting/telecom-telephony-alias-configuration-mode-easyHunting.html
Labels: bug

#888 chore(webpack): add ovh-angular-contact trads
  client/components/contact/contact.js
Labels: bug

#891 fix(telphony): handle empty expired services
  client/components/telecom/telephony/telephony-voip-service.service.js
Labels: bug, quality check ok

#893 chore(webpack): load ovh-angular-otrs trads
  client/components/ovh-angular-otrs/ovh-angular-otrs.js
Labels: bug

#896 fix(telephony): fix bad test
  client/components/telecom/telephony/telephony-voip-service.service.js
Labels: bug, quality check

#908 docs(readme): update readme
  README.md
  yarn.lock
Labels: bug

#909 docs(readme): add contributing and related part
  README.md
Labels: enhancement

#920 fix(package.json): remove unused dependencies
  package.json
  yarn.lock
Labels: bug

#922 build(commitlint): install commitlint with config-angular
  .commitlintrc.js
  .stylelintrc
  commitlint.config.js
  package.json
  yarn.lock
Labels: enhancement, feature

#923 fix(navbar): wait for common translations
  client/components/navbar/navbar.service.js
Labels: bug

#927 build(deps): bump husky to v1.0.0
  package.json
  yarn.lock
Labels: enhancement

#932 docs(readme): fix contributing link
  CONTRIBUTING.md
Labels: bug

#935 fix(translations): add missing translations
  client/app/telecom/telephony/line/assist/telecom-telephony-line-assist.js
  client/app/telecom/telephony/line/fax/campaigns/telecom-telephony-line-fax-campaigns.js
  client/app/telecom/telephony/line/fax/convertToVoicefax/telecom-telephony-line-fax-convertToVoicefax.js
  client/app/telecom/telephony/line/fax/filtering/telecom-telephony-line-fax-filtering.js
  client/app/telecom/telephony/telecom-telephony.js
Labels: bug
