Repository ovh-ux/ovh-manager-telecom, pull requests merged in 2018-11, with the labels that each got.

#1085 refactor: update according to the new cache-loader directory
  .gitignore
  package.json
  yarn.lock
Labels: enhancement

#1079 refactor(wifi): remove column
  client/app/telecom/pack/xdsl/modem/wifi/config/pack-xdsl-modem-wifi-config.html
  client/app/telecom/pack/xdsl/modem/wifi/config/translations/Messages_cs_CZ.xml
  client/app/telecom/pack/xdsl/modem/wifi/config/translations/Messages_de_DE.xml
  client/app/telecom/pack/xdsl/modem/wifi/config/translations/Messages_en_ASIA.xml
  client/app/telecom/pack/xdsl/modem/wifi/config/translations/Messages_en_AU.xml
  client/app/telecom/pack/xdsl/modem/wifi/config/translations/Messages_en_CA.xml
  client/app/telecom/pack/xdsl/modem/wifi/config/translations/Messages_en_GB.xml
  client/app/telecom/pack/xdsl/modem/wifi/config/translations/Messages_en_SG.xml
  client/app/telecom/pack/xdsl/modem/wifi/config/translations/Messages_en_US.xml
  client/app/telecom/pack/xdsl/modem/wifi/config/translations/Messages_es_ES.xml
  client/app/telecom/pack/xdsl/modem/wifi/config/translations/Messages_es_US.xml
  client/app/telecom/pack/xdsl/modem/wifi/config/translations/Messages_fi_FI.xml
  client/app/telecom/pack/xdsl/modem/wifi/config/translations/Messages_fr_CA.xml
  client/app/telecom/pack/xdsl/modem/wifi/config/translations/Messages_fr_FR.xml
  client/app/telecom/pack/xdsl/modem/wifi/config/translations/Messages_it_IT.xml
  client/app/telecom/pack/xdsl/modem/wifi/config/translations/Messages_lt_LT.xml
  client/app/telecom/pack/xdsl/modem/wifi/config/translations/Messages_nl_NL.xml
  client/app/telecom/pack/xdsl/modem/wifi/config/translations/Messages_pl_PL.xml
  client/app/telecom/pack/xdsl/modem/wifi/config/translations/Messages_pt_PT.xml
Labels: enhancement, quality check ok

#1089 fix(deps): update manager-webpack-config to v2.4.6
  package.json
  yarn.lock
Labels: bug

#1088 feat(ipv6): add specific warning message for ipv6 config for zyxel modem
  client/app/telecom/pack/xdsl/access/ipv6/pack-xdsl-access-ipv6.controller.js
  client/app/telecom/pack/xdsl/access/ipv6/pack-xdsl-access-ipv6.html
  client/app/telecom/pack/xdsl/access/ipv6/translations/Messages_fr_FR.xml
  client/app/telecom/pack/xdsl/access/pack-xdsl-access.controller.js
Labels: feature, quality check ok, translation required

#1084 feat(navbar): add tracking for assistance and notifications
  client/components/navbar/navbar-notification.service.js
  client/components/navbar/navbar.service.js
Labels: enhancement, quality check ok

#1078 feat(otb): add search on side menu for OTB
  client/components/telecom/otb/sidebar/over-the-box-sidebar.service.js
Labels: feature, quality check ok

#1091 style(navbar): animate notification icon
  client/app/common/less/navbar.less
  client/components/navbar/navbar-notification.service.js
Labels: enhancement, quality check ok

#1094 fix(deps): upgrade ovh-ui-kit to v2.22.0
  package.json
  yarn.lock
Labels: bug

#1096 fix(deps): upgrade ovh-angular-otrs to v6.3.0
  package.json
  yarn.lock
Labels: bug

#1101 fix(pack.resilisation): set correct template url
  client/app/telecom/pack/resiliation/pack-resiliation.controller.js
Labels: bug

#1107 Feat/guides tracking
  client/app/telecom/dashboard/guides/telecom-dashboard-guides.controller.js
  client/app/telecom/dashboard/guides/telecom-dashboard-guides.html
Labels: enhancement, quality check ok

#1108 fix(deps): update manager-webpack-config to v2.4.7
  package.json
  yarn.lock
Labels: bug

#1109 refactor(components.telephony.service): move task service to tuc
  client/app/telecom/telephony/alias/configuration/changeType/telecom-telephony-alias-configuration-changeType.controller.js
  client/app/telecom/telephony/alias/configuration/tones/oldPabx/telecom-telephony-alias-configuration-tones-oldPabx.controller.js
  client/app/telecom/telephony/billingAccount/phonebook/telecom-telephony-billing-account-phonebook.controller.js
  client/app/telecom/telephony/line/phone/phonebook/telecom-telephony-line-phone-phonebook.controller.js
  client/components/telecom/alias/hunting/sounds/telecom-telephony-alias-hunting-sounds.controller.js
  client/components/telecom/telephony/group/number/feature/conference/telephony-group-number-feature-conference.factory.js
  client/components/telecom/telephony/group/number/feature/ovhPabx/sound/telephony-group-number-feature-ovh-pabx-sound.factory.js
  client/components/telecom/telephony/group/number/feature/redirect/telephony-group-number-feature-redirect.component.controller.js
  client/components/telecom/telephony/group/number/telephony-group-number.factory.js
  client/components/telecom/telephony/service/telecom-telephony-service-task.service.js
  client/telecomUniverseComponents/telecom/telephony/service/index.js
  client/telecomUniverseComponents/telecom/telephony/service/telecom-telephony-service-task.service.js
Labels: :santa: one-manager, quality check ok

#1110 refactor(components.telephony.service): move task service to tuc
  client/telecomUniverseComponents/index.js
  client/telecomUniverseComponents/telecom/telephony/service/index.js
Labels: :santa: one-manager, quality check ok

#1112 fix(deps): upgrade manager-webpack-config to v3.0.0
  package.json
  yarn.lock
Labels: bug

#1092 feat(ftth-otp): add otp configuration for fiber migration
  client/app/telecom/pack/migration/building-details/telecom-pack-migration-building-details.controller.js
  client/app/telecom/pack/migration/building-details/telecom-pack-migration-building-details.html
  client/app/telecom/pack/migration/translations/Messages_fr_FR.xml
  client/telecomUniverseComponents/telecom/pack/migration/pack-migration-process.service.js
  yarn.lock
Labels: feature, quality check ok, translation required

#1116 fix(guides): fix guide urls in over the box
  client/app/telecom/overTheBox/overTheBox.constant.js
Labels: bug, quality check ok

#1087 fix: remove label about hubic upgrade offer into resiliation pack
  client/app/telecom/pack/resiliation/translations/Messages_fr_FR.xml
Labels: quality check ok, translation required

#1122 fix(ui-angular): ovh-ui-angular patch update
  package.json
  yarn.lock
Labels: bug

#1124 fix(pack): pop-up for order ip
  client/app/telecom/pack/xdsl/access/pack-xdsl-access.controller.js
Labels: bug, quality check ok

#1082 feat(wifi): retrieve available channel associated to wifi frequency
  client/app/telecom/pack/xdsl/modem/wifi/config/pack-xdsl-modem-wifi-config.controller.js
  client/app/telecom/pack/xdsl/modem/wifi/config/pack-xdsl-modem-wifi-config.html
  client/app/telecom/pack/xdsl/modem/wifi/config/translations/Messages_fr_FR.xml
Labels: feature, quality check ok, translation required

#1090 feat(modem-tasks): update modem tasks list tab
  client/app/telecom/pack/xdsl/tasks/pack-xdsl-tasks.controller.js
  client/app/telecom/pack/xdsl/tasks/pack-xdsl-tasks.html
  client/app/telecom/pack/xdsl/tasks/translations/Messages_fr_FR.xml
  yarn.lock
Labels: feature, quality check ok, translation required

#1136 fix(deps): upgrade npm-run-all to v4.1.5
  package.json
  yarn.lock
Labels: bug

#1146 fix: apply stylelint rules
  client/app/app.less
  client/app/common/less/navbar.less
  client/app/common/less/ovh-angular-input-number-spinner.less
  client/app/common/less/variables.less
  client/components/sidebar/sidebar.less
  client/components/telecom/telephony/group/consumption/pie-chart/telephony-group-consumption-pie-chart.less
  client/components/telecom/telephony/group/number/telephony-group-number.less
  client/components/telecom/telephony/scheduler/telephony-scheduler.less
  package.json
  yarn.lock
Labels: bug

#1155 ugrade ovh-angular-sidebar-menu to v7.2.2
  package.json
  yarn.lock
Labels: bug

#1148 Feat/reset ovh
  client/app/telecom/pack/xdsl/modem/reset/pack-xdsl-modem-reset.controller.js
  yarn.lock
Labels: feature, quality check ok

#1147 fix(dhcp): fix typo for dchp end address
  client/app/telecom/pack/xdsl/modem/router/dhcp/pack-xdsl-modem-dhcp.html
Labels: bug, quality check ok

#1154 fix(sidebar): change less variable case
  client/components/sidebar/sidebar.less
Labels: bug
