Repository ovh-ux/ovh-manager-telecom, pull requests merged in 2018-02, with the labels that each got.

#561 feat(bulk): add bulk action to fax password
  client/app/telecom/telephony/service/fax/password/telecom-telephony-service-fax-password.controller.js
  client/app/telecom/telephony/service/fax/password/telecom-telephony-service-fax-password.html
  client/app/telecom/telephony/service/fax/password/translations/Messages_fr_FR.xml
Labels: bulk action, feature, quality check ok

#553 feat(bulk): add bulk for phone function keys
  client/app/telecom/telephony/line/phone/programmableKeys/telecom-telephony-line-phone-programmableKeys.controller.js
  client/app/telecom/telephony/line/phone/programmableKeys/telecom-telephony-line-phone-programmableKeys.html
  client/app/telecom/telephony/line/phone/programmableKeys/translations/Messages_fr_FR.xml
  client/components/telecom/telephony/bulkAction/telephony-bulk-action.service.js
  client/components/telecom/voip/feature/line/line/phone/function/voip-feature-line-line-phone-function.factory.js
  client/components/telecom/voip/feature/line/line/phone/function/voip-feature-line-line-phone-function.service.js
Labels: bulk action, enhancement, feature, quality check ok

#554 feat(bulk): fax termination
  client/app/telecom/telephony/fax/management/terminate/telecom-telephony-fax-management-terminate.controller.js
  client/app/telecom/telephony/fax/management/terminate/telecom-telephony-fax-management-terminate.html
  client/app/telecom/telephony/fax/management/terminate/translations/Messages_fr_FR.xml
Labels: bulk action, feature, quality check ok

#562 feat(bulk): bulk action fax settings
  client/app/telecom/telephony/service/fax/settings/telecom-telephony-service-fax-settings.controller.js
  client/app/telecom/telephony/service/fax/settings/telecom-telephony-service-fax-settings.html
  client/app/telecom/telephony/service/fax/settings/translations/Messages_fr_FR.xml
Labels: bulk action, enhancement, quality check ok

#555 Feature/fax/bulk voicemail password
  client/app/telecom/telephony/service/voicemail/password/telecom-telephony-service-voicemail-password.controller.js
  client/app/telecom/telephony/service/voicemail/password/telecom-telephony-service-voicemail-password.html
Labels: bulk action, feature, quality check ok

#534 feat(navbar): update current navbar with new component oui-navbar
  bower.json
  client/app/app.js
  client/app/app.tpl.less
  client/app/common/less/navbar.less
  client/app/common/less/variables.less
  client/app/common/translations/Messages_fr_FR.xml
  client/app/config/all.js
  client/app/telecom/overTheBox/order/order-overTheBox.html
  client/app/telecom/pack/xdsl/modem/pack-xdsl-modem.html
  client/app/telecom/telephony/line/calls/callWaiting/telecom-telephony-line-calls-callWaiting.html
  client/app/telecom/telephony/line/calls/displayNumber/telecom-telephony-line-calls-displayNumber.html
  client/app/telecom/telephony/line/calls/filtering/telecom-telephony-line-calls-filtering.html
  client/assets/images/navbar/icon-assistance.svg
  client/assets/images/navbar/icon-assistance_on.svg
  client/assets/images/navbar/icon-external-link.svg
  client/assets/images/navbar/icon-languages.svg
  client/assets/images/navbar/icon-languages_on.svg
  client/assets/images/navbar/icon-logo-ovh.svg
  client/assets/images/navbar/icon-notifications.svg
  client/assets/images/navbar/icon-notifications_on.svg
  client/assets/images/navbar/icon-user.svg
  client/assets/images/navbar/icon-user_on.svg
  client/components/navbar/navbar.service.js
  client/components/sidebar/sidebar.less
  client/components/sidebar/translations/Messages_fr_FR.xml
  client/components/telecom/telephony/abbreviatedNumbers/import/telecom-telephony-abbreviated-numbers-import.modal.html
  client/components/telecom/telephony/abbreviatedNumbers/telecom-telephony-abbreviated-numbers.modal.html
  client/components/telecom/telephony/bulkAction/modal/telephony-bulk-action-modal.html
  client/components/telecom/telephony/group/number/feature/ovhPabx/tts/create/telephony-group-number-feature-ovh-pabx-tts-create.html
  client/components/telecom/telephony/scheduler/actions/bankHolidays/telephony-scheduler-bank-holidays.html
  client/index.tpl.html
  package-lock.json
  package.json
Labels: enhancement, quality check ok

#572 fix(phone): associate line to phone
  client/components/telecom/telephony/associateDevice/telecom-telephony-associate-device.component.js
Labels: bug, quality check ok

#571 fix(xdsl): ipblock pending order message
  client/app/telecom/pack/xdsl/access/translations/Messages_fr_FR.xml
Labels: bug, quality check ok

#574 fix(navbar): fix navbar promises
  client/components/navbar/navbar.service.js
  client/components/telecom/fax/sidebar/fax-sidebar.service.js
  client/index.tpl.html
Labels: bug

#550 data grid on telephony section (second)
  client/app/telecom/telephony/line/phone/accessories/resume/telecom-telephony-line-phone-accessories-resume.html
  client/app/telecom/telephony/line/phone/programmableKeys/telecom-telephony-line-phone-programmableKeys.html
  client/app/telecom/telephony/service/assist/orders/telecom-telephony-service-assist-orders.controller.js
  client/app/telecom/telephony/service/assist/orders/telecom-telephony-service-assist-orders.html
  client/app/telecom/telephony/service/fax/customDomains/telecom-telephony-service-fax-customDomains.html
Labels: ovh-ui-kit, quality check ok

#523 fix(forward):error message on validation if only one number exists
  client/app/telecom/telephony/line/calls/forward/telecom-telephony-line-calls-forward.html
Labels: bug, quality check ok

#542 data grid in components section
  client/components/telecom/telephony/abbreviatedNumbers/telecom-telephony-abbreviated-numbers.component.js
  client/components/telecom/telephony/abbreviatedNumbers/telecom-telephony-abbreviated-numbers.html
Labels: ovh-ui-kit, quality check ok

#580 fix(billingAccount): add link on dashboard to convert to voicefax state
  client/app/telecom/telephony/billingAccount/dashboard/telecom-telephony-billing-account-dashboard.controller.js
  client/app/telecom/telephony/billingAccount/dashboard/telecom-telephony-billing-account-dashboard.html
  client/app/telecom/telephony/billingAccount/dashboard/translations/Messages_fr_FR.xml
  client/app/telecom/telephony/fax/fax/convertToVoicefax/telecom-telephony-fax-fax-convertToVoiceFax.controller.js
  client/app/telecom/telephony/fax/fax/convertToVoicefax/telecom-telephony-fax-fax-convertToVoicefax.html
  client/app/telecom/telephony/fax/fax/convertToVoicefax/telecom-telephony-fax-fax-convertToVoicefax.js
  client/app/telecom/telephony/fax/translations/Messages_fr_FR.xml
  client/app/telecom/telephony/service/fax/convertToVoicefax/telecom-telephony-service-fax-convertToVoicefax.html
  client/app/telecom/telephony/service/fax/convertToVoicefax/translations/Messages_fr_FR.xml
Labels: bug, enhancement, quality check ok

#579 fix(sip): dipslay public offer details in line header
  client/app/telecom/telephony/line/details/telecom-telephony-line-details.html
  client/app/telecom/telephony/line/details/translations/Messages_fr_FR.xml
  client/components/editable-service-name/editable-service-name.html
Labels: bug, enhancement, quality check ok

#578 fix(line): infrastructure information
  client/app/telecom/telephony/line/details/telecom-telephony-line-details.controller.js
  client/app/telecom/telephony/line/telecom-telephony-line.js
Labels: bug, enhancement, quality check ok

#576 fix(offers): handle old offers previously served
  client/components/telecom/telephony/group/line/group-line-offers.service.js
  client/components/telecom/telephony/group/line/group-line.factory.js
Labels: bug, quality check ok

#570 fix(forward): set default number to current line number on forward na…
  client/app/telecom/telephony/line/calls/forward/telecom-telephony-line-calls-forward.controller.js
Labels: bug, quality check ok

#564 feat(Fax - Assist logs): Add bulk action to assist logs
  client/app/telecom/telephony/service/assist/logs/telecom-telephony-service-assist-logs.controller.js
  client/app/telecom/telephony/service/assist/logs/telecom-telephony-service-assist-logs.html
Labels: bulk action, feature, quality check ok

#560 feat(Line - Sip Password) - Add bulk action for SIP password
  client/app/telecom/telephony/line/management/password/telecom-telephony-line-management-password.controller.js
  client/app/telecom/telephony/line/management/password/telecom-telephony-line-management-password.html
  client/app/telecom/telephony/line/management/password/translations/Messages_fr_FR.xml
  client/components/telecom/voip/feature/line/line/voip-feature-line-line.service.js
Labels: bulk action, feature, quality check ok

#585 Chore/data grid components2
  client/components/telecom/telephony/abbreviatedNumbers/import/telecom-telephony-abbreviated-numbers-import.modal.html
  client/components/telecom/telephony/alias/liveCalls/telecom-telephony-alias-configuration-liveCalls.html
Labels: ovh-ui-kit, quality check

#587 feat(bulk): reactivate link to bulk action for function keys
  client/app/telecom/telephony/line/phone/programmableKeys/telecom-telephony-line-phone-programmableKeys.html
Labels: bulk action, feature, quality check ok

#543 data grid on telephony section (first)
  client/app/telecom/telephony/billingAccount/administration/addGroup/telecom-telephony-billing-account-administration-add-group.controller.js
  client/app/telecom/telephony/billingAccount/administration/linesGroup/telecom-telephony-billing-account-administration-lines-group.controller.js
  client/app/telecom/telephony/billingAccount/administration/linesGroup/telecom-telephony-billing-account-administration-lines-group.html
  client/app/telecom/telephony/billingAccount/billing/bill/telecom-telephony-billing-account-billing-bill.controller.js
  client/app/telecom/telephony/billingAccount/billing/bill/telecom-telephony-billing-account-billing-bill.html
  client/app/telecom/telephony/billingAccount/billing/repaymentHistory/telecom-telephony-billing-account-billing-repayment-history.controller.js
  client/app/telecom/telephony/billingAccount/billing/repaymentHistory/telecom-telephony-billing-account-billing-repayment-history.html
  client/app/telecom/telephony/billingAccount/billing/summary/telecom-telephony-billing-account-billing-summary.controller.js
  client/app/telecom/telephony/billingAccount/billing/summary/telecom-telephony-billing-account-billing-summary.html
  client/app/telecom/telephony/billingAccount/billing/tollfreeHistory/telecom-telephony-billing-account-billing-tollfree-history.controller.js
  client/app/telecom/telephony/billingAccount/billing/tollfreeHistory/telecom-telephony-billing-account-billing-tollfree-history.html
  client/app/telecom/telephony/billingAccount/dashboard/telecom-telephony-billing-account-dashboard.html
  client/app/telecom/telephony/line/phone/accessories/resume/telecom-telephony-line-phone-accessories-resume.html
  client/app/telecom/telephony/line/phone/programmableKeys/telecom-telephony-line-phone-programmableKeys.html
  client/app/telecom/telephony/service/assist/orders/telecom-telephony-service-assist-orders.controller.js
  client/app/telecom/telephony/service/assist/orders/telecom-telephony-service-assist-orders.html
  client/app/telecom/telephony/service/consumption/incomingCalls/telecom-telephony-service-consumption-incomingCalls.controller.js
  client/app/telecom/telephony/service/consumption/incomingCalls/telecom-telephony-service-consumption-incomingCalls.html
  client/app/telecom/telephony/service/consumption/incomingFax/telecom-telephony-service-consumption-incomingFax.controller.js
  client/app/telecom/telephony/service/consumption/incomingFax/telecom-telephony-service-consumption-incomingFax.html
  client/app/telecom/telephony/service/consumption/outgoingCalls/telecom-telephony-service-consumption-outgoingCalls.controller.js
  client/app/telecom/telephony/service/consumption/outgoingCalls/telecom-telephony-service-consumption-outgoingCalls.html
  client/app/telecom/telephony/service/consumption/outgoingFax/telecom-telephony-service-consumption-outgoingFax.controller.js
  client/app/telecom/telephony/service/consumption/outgoingFax/telecom-telephony-service-consumption-outgoingFax.html
  client/app/telecom/telephony/service/fax/customDomains/telecom-telephony-service-fax-customDomains.html
Labels: ovh-ui-kit, quality check ok

#563 feat(bulk): fax coordinates bulk action
  client/app/telecom/telephony/service/contact/telecom-telephony-service-contact.controller.js
  client/app/telecom/telephony/service/contact/telecom-telephony-service-contact.html
  client/components/telecom/telephony/bulkAction/modal/telephony-bulk-action-modal.controller.js
  client/components/telecom/telephony/bulkAction/translations/Messages_fr_FR.xml
Labels: bulk action, enhancement, quality check ok

#586 Bugfix/missing reset port button
  client/app/telecom/pack/xdsl/access/portReset/pack-xdsl-access-port-reset.html
  client/app/telecom/telephony/fax/translations/Messages_fr_FR.xml
  client/app/telecom/telephony/service/fax/convertToVoicefax/telecom-telephony-service-fax-convertToVoicefax.html
Labels: bug, quality check ok

#589 fix(xdsl): pack move eligibility address error messages
  client/app/telecom/pack/move/eligibility/address/pack-move-eligibility-address.component.js
  client/app/telecom/pack/move/eligibility/address/pack-move-eligibility-address.html
  client/app/telecom/pack/move/translations/Messages_fr_FR.xml
Labels: bug, enhancement, quality check ok

#597 Feature/simultaneous calls info
  client/app/telecom/telephony/line/details/telecom-telephony-line-details.controller.js
  client/app/telecom/telephony/line/details/telecom-telephony-line-details.html
  client/app/telecom/telephony/line/details/translations/Messages_fr_FR.xml
  client/app/telecom/telephony/line/telecom-telephony-line.js
Labels: enhancement, quality check ok

#590 fix(order): handle special number for portability
  client/app/telecom/telephony/alias/portability/order/telecom-telephony-alias-portability-order.controller.js
  client/app/telecom/telephony/alias/portability/order/telecom-telephony-alias-portability-order.html
  client/app/telecom/telephony/alias/portability/order/telecom-telephony-alias-portability-order.js
  client/app/telecom/telephony/alias/portability/order/translations/Messages_fr_FR.xml
  client/app/telecom/telephony/billingAccount/orderAlias/special/telecom-telephony-billing-account-orderAlias-special.js
  client/app/telecom/telephony/billingAccount/orderAlias/special/translations/Messages_fr_FR.xml
  client/app/telecom/telephony/translations/Messages_fr_FR.xml
Labels: bug, enhancement, quality check ok

#594 feat(navbar): add hierarchical user menu
  bower.json
  client/app/app.js
  client/app/common/less/navbar.less
  client/app/common/translations/Messages_fr_FR.xml
  client/app/config/all.js
  client/components/navbar/navbar.service.js
  client/index.tpl.html
  package.json
Labels: enhancement, quality check ok

#595 style(*): update layout responsive
  client/components/sidebar/sidebar.less
  client/index.tpl.html
Labels: bug
