Repository ovh-ux/ovh-manager-telecom, pull requests merged in 2018-08, with the labels that each got.

#817 chore(deps): bump ovh-ui-kit and ovh-ui-kit-bs
  package.json
  yarn.lock
Labels: enhancement, ovh-ui-kit

#818 fix(dependencies): remove duplicates vendor
  dependencies.json
Labels: bug, enhancement

#820 fix(*): use correct oui-switch semantic
  client/app/telecom/sms/receivers/add/telecom-sms-receivers-add.html
  client/app/telecom/telephony/line/calls/callWaiting/telecom-telephony-line-calls-callWaiting.html
  client/app/telecom/telephony/line/phone/configuration/telecom-telephony-line-phone-configuration.html
  client/app/telecom/telephony/service/voicemail/options/telecom-telephony-service-voicemail-options.html
  client/components/telecom/telephony/group/number/feature/conference/telephony-group-number-feature-conference.html
  client/components/telecom/telephony/scheduler/events/telephony-scheduler-events.html
Labels: bug

#824 fix(telephony group): alert message style
  client/app/telecom/telephony/billingAccount/administration/addGroup/telecom-telephony-billing-account-administration-add-group.html
Labels: bug, quality check ok

#826 hotfix(telephony): allow selecting a billing address
  dependencies.json
  package.json
Labels: bug, quality check ok

#829 fix(telephony.group): add oui-button class
  client/app/telecom/telephony/billingAccount/administration/addGroup/telecom-telephony-billing-account-administration-add-group.html
Labels: bug, quality check ok

#834 fix(telephony.orderalias.geographical): call api with zone.city
  client/app/telecom/telephony/billingAccount/orderAlias/geographical/telecom-telephony-billing-account-orderAlias-geographical.controller.js
Labels: bug

#823 Feature/special transfer
  client/app/config/all.js
  client/app/telecom/telephony/alias/special/fees/telecom-telephony-alias-special-fees.controller.js
  client/app/telecom/telephony/alias/special/fees/telecom-telephony-alias-special-fees.html
  client/app/telecom/telephony/alias/special/fees/telecom-telephony-alias-special-fees.js
  client/app/telecom/telephony/alias/special/fees/translations/Messages_fr_FR.xml
  client/app/telecom/telephony/alias/special/rsva/telecom-telephony-alias-special-rsva.controller.js
  client/app/telecom/telephony/alias/special/rsva/telecom-telephony-alias-special-rsva.html
  client/app/telecom/telephony/alias/special/rsva/telecom-telephony-alias-special-rsva.js
  client/app/telecom/telephony/alias/special/rsva/translations/Messages_fr_FR.xml
  client/app/telecom/telephony/alias/special/telecom-telephony-alias-special.html
  client/app/telecom/telephony/alias/special/telecom-telephony-alias-special.js
  client/app/telecom/telephony/alias/special/transfer/telecom-telephony-alias-special-transfer.controller.js
  client/app/telecom/telephony/alias/special/transfer/telecom-telephony-alias-special-transfer.html
  client/app/telecom/telephony/alias/special/transfer/telecom-telephony-alias-special-transfer.js
  client/app/telecom/telephony/alias/special/transfer/translations/Messages_fr_FR.xml
  client/app/telecom/telephony/alias/special/translations/Messages_fr_FR.xml
  client/app/telecom/telephony/alias/telecom-telephony-alias-main.view.html
  client/app/telecom/telephony/alias/telecom-telephony-alias.controller.js
  client/app/telecom/telephony/alias/telecom-telephony-alias.js
  client/app/telecom/telephony/alias/translations/Messages_fr_FR.xml
  client/app/telecom/telephony/translations/Messages_fr_FR.xml
  client/components/telecom/telephony/group/number/telephony-group-number.factory.js
Labels: feature, quality check ok

#837 chore(deps): bump ovh-angular-otrs
  yarn.lock
Labels: enhancement

#840 fix(oui-action-menu-item): remove deprecated text attribut
  client/app/telecom/pack/xdsl/modem/wifi/config/pack-xdsl-modem-wifi-config.html
  client/app/telecom/sms/options/response/telecom-sms-options-response.html
  client/app/telecom/sms/sms/templates/telecom-sms-sms-templates.html
  client/app/telecom/sms/users/telecom-sms-users.html
  client/app/telecom/telephony/billingAccount/billing/bill/telecom-telephony-billing-account-billing-bill.html
  client/app/telecom/telephony/billingAccount/billing/repaymentHistory/telecom-telephony-billing-account-billing-repayment-history.html
  client/app/telecom/telephony/billingAccount/billing/tollfreeHistory/telecom-telephony-billing-account-billing-tollfree-history.html
  client/app/telecom/telephony/billingAccount/dashboard/telecom-telephony-billing-account-dashboard.html
  client/app/telecom/telephony/line/phone/programmableKeys/telecom-telephony-line-phone-programmableKeys.html
Labels: bug

#816 fix(connected devices missing): refresh connected devices
  client/app/telecom/pack/xdsl/modem/connectedDevices/pack-xdsl-modem-connectedDevices.controller.js
  client/app/telecom/pack/xdsl/modem/connectedDevices/pack-xdsl-modem-connectedDevices.html
Labels: bug, quality check

#846 chore(build): Install right smarttag
  Makefile
Labels: enhancement

#848 fix(packxdsl.name): update display name
  client/app/telecom/pack/pack.controller.js
Labels: bug, quality check ok

#852 fix(call forwarding): call forwarding selection
  client/app/telecom/telephony/line/calls/forward/telecom-telephony-line-calls-forward.controller.js
Labels: bug, quality check ok

#854 fix(guide-url): sms guide url not working
  client/app/telecom/sms/telecom-sms.constant.js
Labels: bug, quality check ok

#855 feat(xdsl): auto diagnostic new version
  client/app/telecom/pack/xdsl/access/diagnostic/pack-xdsl-access-diagnostic.controller.js
  client/app/telecom/pack/xdsl/access/diagnostic/pack-xdsl-access-diagnostic.html
  client/app/telecom/pack/xdsl/access/diagnostic/pack-xdsl-access-diagnostic.js
  client/app/telecom/pack/xdsl/access/diagnostic/translations/Messages_fr_FR.xml
  client/app/telecom/pack/xdsl/access/translations/Messages_fr_FR.xml
  client/assets/images/diagnostic/filtre-adsl.png
  client/assets/images/diagnostic/human-good.svg
  client/assets/images/diagnostic/human-speedAndGraphic.svg
  client/assets/images/diagnostic/human-think.svg
  dependencies.json
  package.json
  yarn.lock
Labels: feature, quality check ok, translation required
