Repository ovh-ux/ovh-manager-telecom, pull requests merged in 2018-06, with the labels that each got.

#729 fix(telephony add group order): fix validation icon
  client/app/telecom/telephony/billingAccount/administration/addGroup/telecom-telephony-billing-account-administration-add-group.html
Labels: bug

#705 fix(navbar): language button position and format
  client/components/navbar/navbar.service.js
Labels: enhancement, quality check ok

#731 fix(telephony voicemail options): add word-break
  client/app/telecom/telephony/service/voicemail/options/telecom-telephony-service-voicemail-options.html
Labels: bug

#728 fix(sms options recredit): amount typo
  client/app/telecom/sms/options/recredit/translations/Messages_fr_FR.xml
  client/app/telecom/sms/options/recredit/update/telecom-sms-options-recredit-update.html
Labels: bug

#726 Feature/new navbar notification
  client/app/app.js
  client/app/app.mock.js
  client/app/common/translations/Messages_fr_FR.xml
  client/components/me-alerts/me-alerts.config.js
  client/components/me-alerts/me-alerts.less
  client/components/me-alerts/translations/Messages_cs_CZ.xml
  client/components/me-alerts/translations/Messages_de_DE.xml
  client/components/me-alerts/translations/Messages_en_ASIA.xml
  client/components/me-alerts/translations/Messages_en_AU.xml
  client/components/me-alerts/translations/Messages_en_CA.xml
  client/components/me-alerts/translations/Messages_en_GB.xml
  client/components/me-alerts/translations/Messages_en_SG.xml
  client/components/me-alerts/translations/Messages_en_US.xml
  client/components/me-alerts/translations/Messages_es_ES.xml
  client/components/me-alerts/translations/Messages_es_US.xml
  client/components/me-alerts/translations/Messages_fi_FI.xml
  client/components/me-alerts/translations/Messages_fr_CA.xml
  client/components/me-alerts/translations/Messages_fr_FR.xml
  client/components/me-alerts/translations/Messages_it_IT.xml
  client/components/me-alerts/translations/Messages_lt_LT.xml
  client/components/me-alerts/translations/Messages_nl_NL.xml
  client/components/me-alerts/translations/Messages_pl_PL.xml
  client/components/me-alerts/translations/Messages_pt_PT.xml
  client/components/navbar/navbar-notification.service.js
  client/components/navbar/navbar.service.js
Labels: feature, quality check ok

#737 fix(telephony fax): contact view typo
  client/app/telecom/telephony/fax/contact/telecom-telephony-fax-contact.js
Labels: bug

#740 Change the parameters to upload tones, give a document id instead of a temporary url
  client/app/telecom/telephony/alias/configuration/tones/oldPabx/telecom-telephony-alias-configuration-tones-oldPabx.controller.js
  client/app/telecom/telephony/line/tones/telecom-telephony-line-tones.controller.js
Labels: bug, quality check ok

#747 fix(navbar): access to static methods
  client/components/navbar/navbar.service.js
Labels: bug
