Repository ovh-ux/ovh-manager-telecom, pull requests merged in 2018-03, with the labels that each got.

#602 chore(deps): bump ovh-ui-kit-bs to v1.0.8
  package-lock.json
  package.json
Labels: enhancement

#596 fix(forward): forward numbers option limited to current billing accou…
  client/app/telecom/telephony/line/calls/forward/nature/telecom-telephony-line-calls-forward-nature.factory.js
  client/app/telecom/telephony/line/calls/forward/phoneNumber/telecom-telephony-line-calls-forward-phoneNumber.factory.js
  client/app/telecom/telephony/line/calls/forward/telecom-telephony-line-calls-forward.controller.js
  client/app/telecom/telephony/line/calls/forward/telecom-telephony-line-calls-forward.html
  client/app/telecom/telephony/line/calls/forward/telecom-telephony-line-calls-forward.service.js
  client/app/telecom/telephony/line/calls/forward/translations/Messages_fr_FR.xml
Labels: bug, enhancement, quality check ok

#608 feat(portability): add "execute asap" option for desired date
  client/app/telecom/telephony/alias/portability/order/telecom-telephony-alias-portability-order.controller.js
  client/app/telecom/telephony/alias/portability/order/telecom-telephony-alias-portability-order.html
  client/app/telecom/telephony/alias/portability/order/translations/Messages_fr_FR.xml
Labels: feature, quality check ok

#583 feat(Alias - Order international alias): Remove required fields in belgium case
  client/app/telecom/telephony/billingAccount/orderAlias/coordinate/identity/telecom-telephony-billing-account-orderAlias-coordinate-identity.html
Labels: bug, quality check ok

#609 bug(Line - Dashboard): Removing extra behaviour that causes weird stuff through different browsers
  client/components/editable-service-name/editable-service-name.directive.js
Labels: bug, quality check ok

#552 feat(Line - Restriction MGCP to IP): Add bulk action to restriction
  client/app/telecom/telephony/line/phone/mgcpIpRestriction/telecom-telephony-line-phone-mgcpIpRestriction.controller.js
  client/app/telecom/telephony/line/phone/mgcpIpRestriction/telecom-telephony-line-phone-mgcpIpRestriction.html
  client/app/telecom/telephony/line/phone/mgcpIpRestriction/translations/Messages_fr_FR.xml
Labels: bulk action, feature, quality check ok

#615 bug(Line - Sound adding popover): Select unique item when available
  client/components/telecom/telephony/group/number/feature/ovhPabx/sound/list/telephony-group-number-feature-ovh-pabx-sound-list.component.controller.js
Labels: bug, enhancement, quality check ok

#610 chore(line simultaneous calls): change of multi requests to get prices
  client/app/common/translations/Messages_fr_FR.xml
  client/app/telecom/telephony/line/calls/simultaneousLines/telecom-telephony-line-calls-simultaneousLines.controller.js
  client/app/telecom/telephony/line/calls/simultaneousLines/telecom-telephony-line-calls-simultaneousLines.html
Labels: enhancement, quality check ok

#626 feat(All - Docs): Change 'Telephony' docs link
  client/app/config/all.js
Labels: enhancement, feature

#627 feat(All - Docs): Change 'Telephony' docs link
  client/app/config/all.js
Labels: bug, quality check ok

#623 bug(Line - Configuration): Wrong label on speaker volume
  client/app/telecom/telephony/line/phone/configuration/translations/Messages_fr_FR.xml
Labels: bug, quality check ok

#616 bug(Line - Configuration): Removing interactive menu when feature type is CloudHunting
  client/components/telecom/telephony/group/number/feature/ovhPabx/dialplan/extension/rule/edit/telephony-group-number-feature-ovh-pabx-dialplan-extension-rule-edit.controller.js
Labels: bug, enhancement, quality check ok

#581 feat(Alias - EasyHunting): Add warning modal to member addition
  client/app/telecom/telephony/alias/configuration/agents/ovhPabx/telecom-telephony-alias-configuration-agents-ovhPabx-modal.component.js
  client/app/telecom/telephony/alias/configuration/agents/ovhPabx/telecom-telephony-alias-configuration-agents-ovhPabx-modal.html
  client/app/telecom/telephony/alias/configuration/agents/ovhPabx/telecom-telephony-alias-configuration-agents-ovhPabx.controller.js
  client/app/telecom/telephony/alias/configuration/agents/ovhPabx/telecom-telephony-alias-configuration-agents-ovhPabx.js
  client/app/telecom/telephony/alias/configuration/agents/translations/Messages_fr_FR.xml
  client/app/telecom/telephony/alias/configuration/queues/ovhPabx/telecom-telephony-alias-configuration-queues-ovhPabx-modal.component.js
  client/app/telecom/telephony/alias/configuration/queues/ovhPabx/telecom-telephony-alias-configuration-queues-ovhPabx-modal.html
  client/app/telecom/telephony/alias/configuration/queues/ovhPabx/telecom-telephony-alias-configuration-queues-ovhPabx.controller.js
  client/app/telecom/telephony/alias/configuration/queues/ovhPabx/telecom-telephony-alias-configuration-queues-ovhPabx.js
  client/app/telecom/telephony/alias/configuration/queues/translations/Messages_fr_FR.xml
  client/components/telecom/telephony/alias/members/telecom-telephony-alias-members-add-modal.component.js
  client/components/telecom/telephony/alias/members/telecom-telephony-alias-members-add-modal.html
  client/components/telecom/telephony/alias/members/telecom-telephony-alias-members-add.component.js
  client/components/telecom/telephony/alias/members/translations/Messages_fr_FR.xml
  client/components/telecom/telephony/alias/records/telecom-telephony-alias-records.html
  client/components/telecom/telephony/group/number/feature/ovhPabx/dialplan/edit/telephony-group-number-feature-ovh-pabx-dialplan-edit.html
  client/components/telecom/telephony/group/number/feature/ovhPabx/menu/entry/edit/telephony-group-number-feature-ovh-pabx-menu-entry-edit.html
Labels: enhancement, feature, quality check ok

#497 bugfix(Portability): SocialReason & Offer misunderstanding
  client/app/telecom/telephony/alias/portability/order/telecom-telephony-alias-portability-order.controller.js
Labels: bug, quality check ok

#588 bug(Modem - Configuration): Mis-word on toggling WiFi
  client/app/telecom/pack/xdsl/modem/wifi/pack-xdsl-modem-wifi.html
  client/app/telecom/pack/xdsl/modem/wifi/translations/Messages_fr_FR.xml
Labels: bug, quality check ok

#641 fix(events): duplicates on changing event in creation
  client/app/telecom/telephony/line/calls/events/telecom-telephony-line-calls-events.controller.js
  client/components/telecom/telephony/scheduler/events/telephony-scheduler-events.component.controller.js
  client/components/telecom/telephony/scheduler/telephony-scheduler.directive.js
Labels: bug, quality check ok

#628 fix(Alias - Configuration): Working on DTMF modal
  client/components/telecom/telephony/group/number/feature/ovhPabx/menu/entry/edit/telephony-group-number-feature-ovh-pabx-menu-entry-edit.html
  client/components/telecom/telephony/group/number/feature/ovhPabx/menu/telephony-group-number-feature-ovh-pabx-menu.less
Labels: bug, quality check ok

#624 bug(Xdsl - DHCP): Allow empty Secondary DNS value
  client/app/telecom/pack/xdsl/modem/router/dhcp/pack-xdsl-modem-dhcp.factory.js
  client/app/telecom/pack/xdsl/modem/router/dhcp/pack-xdsl-modem-dhcp.html
Labels: bug, quality check ok

#638 feat(Line - Management): Move 'MGCP to IP restriction' button
  client/app/telecom/telephony/line/management/mgcpIpRestriction/telecom-telephony-line-mgcpIpRestriction.controller.js
  client/app/telecom/telephony/line/management/mgcpIpRestriction/telecom-telephony-line-mgcpIpRestriction.html
  client/app/telecom/telephony/line/management/mgcpIpRestriction/telecom-telephony-line-mgcpIpRestriction.js
  client/app/telecom/telephony/line/management/mgcpIpRestriction/translations/Messages_cs_CZ.xml
  client/app/telecom/telephony/line/management/mgcpIpRestriction/translations/Messages_de_DE.xml
  client/app/telecom/telephony/line/management/mgcpIpRestriction/translations/Messages_en_ASIA.xml
  client/app/telecom/telephony/line/management/mgcpIpRestriction/translations/Messages_en_AU.xml
  client/app/telecom/telephony/line/management/mgcpIpRestriction/translations/Messages_en_CA.xml
  client/app/telecom/telephony/line/management/mgcpIpRestriction/translations/Messages_en_GB.xml
  client/app/telecom/telephony/line/management/mgcpIpRestriction/translations/Messages_en_SG.xml
  client/app/telecom/telephony/line/management/mgcpIpRestriction/translations/Messages_en_US.xml
  client/app/telecom/telephony/line/management/mgcpIpRestriction/translations/Messages_es_ES.xml
  client/app/telecom/telephony/line/management/mgcpIpRestriction/translations/Messages_es_US.xml
  client/app/telecom/telephony/line/management/mgcpIpRestriction/translations/Messages_fi_FI.xml
  client/app/telecom/telephony/line/management/mgcpIpRestriction/translations/Messages_fr_CA.xml
  client/app/telecom/telephony/line/management/mgcpIpRestriction/translations/Messages_fr_FR.xml
  client/app/telecom/telephony/line/management/mgcpIpRestriction/translations/Messages_it_IT.xml
  client/app/telecom/telephony/line/management/mgcpIpRestriction/translations/Messages_lt_LT.xml
  client/app/telecom/telephony/line/management/mgcpIpRestriction/translations/Messages_nl_NL.xml
  client/app/telecom/telephony/line/management/mgcpIpRestriction/translations/Messages_pl_PL.xml
  client/app/telecom/telephony/line/management/mgcpIpRestriction/translations/Messages_pt_PT.xml
  client/app/telecom/telephony/line/management/telecom-telephony-line-management.controller.js
  client/app/telecom/telephony/line/management/translations/Messages_fr_FR.xml
  client/app/telecom/telephony/line/phone/mgcpIpRestriction/telecom-telephony-line-phone-mgcpIpRestriction.js
  client/app/telecom/telephony/line/phone/telecom-telephony-line-phone.controller.js
  client/app/telecom/telephony/line/phone/translations/Messages_fr_FR.xml
Labels: enhancement, feature, quality check ok

#600 feat(line plug&phone): add detach line phone attached to another line
  client/app/telecom/telephony/line/phone/order/telecom-telephony-line-phone-order.controller.js
  client/app/telecom/telephony/line/phone/order/telecom-telephony-line-phone-order.html
  client/app/telecom/telephony/line/phone/order/translations/Messages_fr_FR.xml
  client/components/telecom/telephony/associateDevice/telecom-telephony-associate-device.component.js
  client/components/telecom/telephony/associateDevice/telecom-telephony-associate-device.html
  client/components/telecom/telephony/group/line/phone/line-phone.factory.js
  client/components/telecom/telephony/telephony-mediator.service.js
Labels: enhancement, feature, quality check ok

#582 bug(Line - Plug & Phone): Static URL in Plug & Phone
  client/app/telecom/telephony/line/assist/troubleshooting/procedure/siemens/telecom-telephony-line-assist-troubleshooting-procedure-siemens.html
  client/app/telecom/telephony/line/assist/troubleshooting/procedure/telecom-telephony-line-assist-troubleshooting-procedure.controller.js
  client/app/telecom/telephony/line/assist/troubleshooting/procedure/translations/Messages_cs_CZ.xml
  client/app/telecom/telephony/line/assist/troubleshooting/procedure/translations/Messages_de_DE.xml
  client/app/telecom/telephony/line/assist/troubleshooting/procedure/translations/Messages_en_AU.xml
  client/app/telecom/telephony/line/assist/troubleshooting/procedure/translations/Messages_en_CA.xml
  client/app/telecom/telephony/line/assist/troubleshooting/procedure/translations/Messages_en_GB.xml
  client/app/telecom/telephony/line/assist/troubleshooting/procedure/translations/Messages_en_US.xml
  client/app/telecom/telephony/line/assist/troubleshooting/procedure/translations/Messages_es_US.xml
  client/app/telecom/telephony/line/assist/troubleshooting/procedure/translations/Messages_fi_FI.xml
  client/app/telecom/telephony/line/assist/troubleshooting/procedure/translations/Messages_fr_CA.xml
  client/app/telecom/telephony/line/assist/troubleshooting/procedure/translations/Messages_fr_FR.xml
  client/app/telecom/telephony/line/assist/troubleshooting/procedure/translations/Messages_nl_NL.xml
  client/app/telecom/telephony/line/assist/troubleshooting/procedure/translations/Messages_pl_PL.xml
  client/app/telecom/telephony/line/assist/troubleshooting/procedure/translations/Messages_pt_PT.xml
Labels: bug, quality check ok

#631 feat(Pack - Xdsl) Adding page in case of missing RIO in invalid XDSL orders
  client/app/telecom/pack/xdsl/missingRio/pack-xdsl-missing-rio.controller.js
  client/app/telecom/pack/xdsl/missingRio/pack-xdsl-missing-rio.html
  client/app/telecom/pack/xdsl/missingRio/pack-xdsl-missing-rio.js
  client/app/telecom/pack/xdsl/missingRio/translations/Messages_fr_FR.xml
  client/app/telecom/pack/xdsl/pack-xdsl.controller.js
  client/app/telecom/pack/xdsl/pack-xdsl.html
Labels: enhancement, feature, quality check ok

#637 feat(bulk): fax filtering bulk action
  client/app/telecom/telephony/service/fax/filtering/telecom-telephony-service-fax-filtering.controller.js
  client/app/telecom/telephony/service/fax/filtering/telecom-telephony-service-fax-filtering.html
  client/app/telecom/telephony/service/fax/filtering/translations/Messages_fr_FR.xml
Labels: bulk action, feature, quality check ok

#642 feat(Line - Interactive Menu): Show current interactive menu in menu listing
  client/components/telecom/telephony/group/number/feature/ovhPabx/menu/list/telephony-group-number-feature-ovh-pabx-menu-list.html
Labels: bug, quality check ok

#649 chore: update UI Kit version
  package-lock.json
  package.json
Labels: bug, quality check ok

#617 feat(abbreviatedNumber): apply modal forms components on add number
  bower.json
  client/app/app.js
  client/app/app.tpl.less
  client/app/common/translations/Messages_fr_FR.xml
  client/components/telecom/telephony/abbreviatedNumbers/telecom-telephony-abbreviated-numbers.modal.html
  client/components/telecom/telephony/abbreviatedNumbers/telecom-telephony-abbreviated-numbers.modal.js
  client/components/telecom/telephony/abbreviatedNumbers/translations/Messages_fr_FR.xml
  package-lock.json
  package.json
  yarn.lock
Labels: quality check ok

#656 chore: bump version of ovh-ui-kit-bs
  bower.json
  client/app/app.tpl.less
  package-lock.json
Labels: enhancement, ovh-ui-kit

#646 fix(Line - Troubleshooting): Specific label for Yealink W56P
  client/app/telecom/telephony/line/assist/troubleshooting/autoConfig/telecom-telephony-line-assist-troubleshooting-auto-config.html
  client/app/telecom/telephony/line/assist/troubleshooting/autoConfig/translations/Messages_fr_FR.xml
Labels: enhancement, quality check ok

#645 fix(Line - Troubleshooting): Specific label for Thomson ST2030
  client/app/telecom/telephony/line/assist/troubleshooting/manualConfig/telecom-telephony-line-assist-troubleshooting-manual-config.html
  client/app/telecom/telephony/line/assist/troubleshooting/manualConfig/translations/Messages_fr_FR.xml
Labels: enhancement, quality check ok

#618 feat(telephony time conditions): add export/import options
  client/app/telecom/telephony/alias/configuration/timeCondition/easyHunting/telecom-telephony-alias-configuration-time-condition-easy-hunting.controller.js
  client/app/telecom/telephony/alias/configuration/timeCondition/easyHunting/telecom-telephony-alias-configuration-time-condition-easy-hunting.html
  client/app/telecom/telephony/alias/configuration/timeCondition/easyHunting/telecom-telephony-alias-configuration-time-condition-easy-hunting.js
  client/app/telecom/telephony/alias/configuration/timeCondition/oldPabx/telecom-telephony-alias-configuration-time-condition-old-pabx.controller.js
  client/app/telecom/telephony/alias/configuration/timeCondition/oldPabx/telecom-telephony-alias-configuration-time-condition-old-pabx.html
  client/app/telecom/telephony/alias/configuration/timeCondition/oldPabx/telecom-telephony-alias-configuration-time-condition-old-pabx.js
  client/app/telecom/telephony/line/calls/timeCondition/telecom-telephony-line-calls-time-condition.controller.js
  client/app/telecom/telephony/line/calls/timeCondition/telecom-telephony-line-calls-time-condition.html
  client/app/telecom/telephony/line/calls/timeCondition/telecom-telephony-line-calls-time-condition.js
  client/app/telecom/telephony/service/time-condition/import/telecom-telephony-service-time-condition-import.controller.js
  client/app/telecom/telephony/service/time-condition/import/telecom-telephony-service-time-condition-import.html
  client/app/telecom/telephony/translations/Messages_fr_FR.xml
  client/components/telecom/telephony/service/time-condition-configuration/telecom-telephony-service-time-condition-configuration.service.js
Labels: feature, quality check ok

#639 Chore/generate changelog
  .scriptsrc
  CHANGELOG.md
  Gruntfile.js
  Makefile
  commitlint.config.js
  package.json
  yarn.lock
Labels: enhancement
