Repository ovh-ux/ovh-manager-telecom, pull requests merged in 2018-07, with the labels that each got.

#741 feat(navbar): add notification placeholder translations
  client/app/app.js
  client/app/common/translations/Messages_fr_FR.xml
  client/components/navbar/navbar-notification.service.js
Labels: feature, quality check

#751 fix(telephony options group): use heading attribut on oui-back-button
  bower.json
  client/app/telecom/telephony/billingAccount/administration/optionsGroup/telecom-telephony-billing-account-administration-options-group.html
  package-lock.json
Labels: enhancement

#750 Chore/kill bower
  .bowerrc
  .editorconfig
  .gitignore
  Gruntfile.js
  Makefile
  README.md
  bower.json
  ci/add-dependency.js
  client/app/app-scss.scss
  client/app/app.js
  client/app/app.mock.js
  client/app/app.tpl.less
  client/app/telecom/pack/slots/voipLine/activation/pack-voipLine-activation.controller.spec.js
  client/app/telecom/pack/xdsl/access/pack-xdsl-access.controller.spec.js
  client/app/telecom/pack/xdsl/access/rateLimit/xdsl-access-lns-ratelimit.controller.spec.js
  client/app/telecom/pack/xdsl/modem/bridgeMode/pack-xdsl-modem-bridgeMode.controller.spec.js
  client/app/telecom/pack/xdsl/modem/connectedDevices/pack-xdsl-modem-connectedDevices.controller.spec.js
  client/app/telecom/pack/xdsl/modem/dmz/pack-xdsl-modem-dmz.controller.spec.js
  client/app/telecom/pack/xdsl/modem/firewall/pack-xdsl-modem-firewall.controller.spec.js
  client/app/telecom/pack/xdsl/modem/managedByOvh/pack-xdsl-modem-managedByOvh.controller.spec.js
  client/app/telecom/pack/xdsl/modem/mtu/pack-xdsl-modem-mtu.controller.spec.js
  client/app/telecom/pack/xdsl/modem/pack-xdsl-modem.controller.spec.js
  client/app/telecom/pack/xdsl/modem/reboot/pack-xdsl-modem-reboot.controller.spec.js
  client/app/telecom/pack/xdsl/modem/reset/pack-xdsl-modem-reset.controller.spec.js
  client/app/telecom/pack/xdsl/modem/wifi/pack-xdsl-modem-wifi.controller.spec.js
  client/app/telecom/telephony/billingAccount/orderAlias/telecom-telephony-billing-account-orderAlias.controller.spec.js
  client/index.tpl.html
  dependencies.json
  karma.conf.tpl.js
  package-lock.json
  package.json
  server/config/express.js
  server/routes.js
  yarn.lock
Labels: enhancement, quality check ok

#760 fix(yarn): new-version parameter
  Makefile
Labels: bug

#765 fix(xdsl pack): remove background color for promotion code
  client/app/telecom/pack/slots/promotionCode/pack-promotionCode.html
Labels: bug

#757 fix(telephony): restore easyhunting translations
  client/app/telecom/telephony/alias/configuration/mode/easyHunting/translations/Messages_fr_FR.xml
Labels: bug, quality check ok

#770 fix(telephony): add plugNFax lines in display Number selection
  client/app/telecom/telephony/line/calls/displayNumber/telecom-telephony-line-calls-displayNumber.html
Labels: bug, quality check ok

#769 fix(alias): fix list of sounds popup in configuration
  client/components/telecom/alias/hunting/sounds/telecom-telephony-alias-hunting-sounds.html
Labels: bug, quality check ok

#756 Feat/xdsl emailpro
  client/app/config/all.js
  client/app/telecom/pack/pack.controller.js
  client/app/telecom/pack/pack.js
  client/app/telecom/pack/slots/emailPro/add/pack-emailPro-add.controller.js
  client/app/telecom/pack/slots/emailPro/add/pack-emailPro-add.html
  client/app/telecom/pack/slots/emailPro/add/pack-emailPro-add.js
  client/app/telecom/pack/slots/emailPro/add/translations/Messages_fr_FR.xml
  client/app/telecom/pack/slots/emailPro/detail/pack-emailPro-detail.controller.js
  client/app/telecom/pack/slots/emailPro/detail/pack-emailPro-detail.html
  client/app/telecom/pack/slots/emailPro/detail/pack-emailPro-detail.js
  client/app/telecom/pack/slots/emailPro/detail/translations/Messages_fr_FR.xml
  client/app/telecom/pack/slots/emailPro/pack-emailPro.controller.js
  client/app/telecom/pack/slots/emailPro/pack-emailPro.html
  client/app/telecom/pack/slots/emailPro/pack.emailPro.constant.js
  client/app/telecom/pack/slots/emailPro/translations/Messages_fr_FR.xml
  client/app/telecom/pack/translations/Messages_fr_FR.xml
  yarn.lock
Labels: feature, quality check ok

#767 fix(trunk): input number validation error useless
  client/app/telecom/telephony/line/calls/simultaneousLines/trunk/telecom-telephony-line-trunk-calls-simultaneousLines.html
  client/app/telecom/telephony/line/calls/simultaneousLines/trunk/telecom-telephony-line-trunk-calls.simultaneousLines.js
Labels: bug, quality check ok

#778 Fix/ip sip restrictions
  client/app/telecom/telephony/line/management/telecom-telephony-line-management.controller.js
Labels: bug, quality check ok

#768 Fix - Abbreviated Number - API and validation change
  client/app/telecom/telephony/billingAccount/abbreviatedNumbers/telecom-telephony-abbreviatedNumbers.controller.js
  client/app/telecom/telephony/line/calls/abbreviatedNumbers/telecom-telephony-line-calls-abbreviatedNumbers.controller.js
  client/components/telecom/telephony/abbreviatedNumbers/telecom-telephony-abbreviated-numbers.modal.html
  client/components/telecom/telephony/abbreviatedNumbers/translations/Messages_fr_FR.xml
Labels: bug, quality check ok, translation required

#773 Bugfix/mfrww 438
  client/app/telecom/telephony/billingAccount/orderAlias/geographical/telecom-telephony-billing-account-orderAlias-geographical.controller.js
  client/app/telecom/telephony/billingAccount/orderAlias/geographical/telecom-telephony-billing-account-orderAlias-geographical.html
  package.json
  yarn.lock
Labels: bug, quality check ok

#789 Fix/portability param
  client/app/telecom/telephony/alias/portability/order/telecom-telephony-alias-portability-order.controller.js
Labels: bug, quality check ok

#793 fix(line registration): select the first element of the array
  client/app/telecom/telephony/line/details/telecom-telephony-line-details.controller.js
Labels: bug

#797 chore(deps): bump ovh-angular-otrs to v6.1.2
  yarn.lock
Labels: enhancement

#783 fix(telephony): force forward refresh
  client/app/telecom/telephony/line/calls/forward/telecom-telephony-line-calls-forward.controller.js
Labels: bug, quality check ok

#801 Bugfix/delete menu action
  client/components/telecom/telephony/group/number/feature/ovhPabx/menu/telephony-group-number-feature-ovh-pabx-menu.component.controller.js
Labels: bug, quality check ok

#803 Perf/improve grunt jsonmerge task
  Gruntfile.js
Labels: enhancement

#809 fix(line.tones): music configuration for priceplan
  client/app/telecom/telephony/line/telecom-telephony-line-main.view.html
Labels: bug, quality check ok

#815 fix(telephony): missing alias options for function keys line phone
  client/app/telecom/telephony/line/phone/programmableKeys/edit/telecom-telephony-line-phone-programmableKeys-edit.controller.js
Labels: bug, quality check ok
