Repository ovh-ux/ovh-manager-telecom, pull requests merged in 2018-04, with the labels that each got.

#657 feat(alias): add infos to sounds/menus configuration, fix menu creation
  client/app/telecom/telephony/alias/configuration/ovhPabx/menus/telecom-telephony-alias-configuration-ovhPabx-menus.html
  client/app/telecom/telephony/alias/configuration/ovhPabx/menus/translations/Messages_fr_FR.xml
  client/app/telecom/telephony/alias/configuration/ovhPabx/sounds/telecom-telephony-alias-configuration-ovhPabx-sounds.html
  client/app/telecom/telephony/alias/configuration/ovhPabx/sounds/translations/Messages_fr_FR.xml
  client/components/telecom/telephony/group/number/feature/ovhPabx/menu/telephony-group-number-feature-ovh-pabx-menu.component.controller.js
  client/components/telecom/telephony/group/number/feature/ovhPabx/menu/telephony-group-number-feature-ovh-pabx-menu.html
Labels: bug, enhancement, quality check ok

#665 chore(gruntfile): remove open task
  Gruntfile.js
  package-lock.json
  package.json
Labels: enhancement

#664 chore: git push on post-version
  bower.json
  package.json
Labels: bug

#668 feat: show app URL on terminal
  package-lock.json
  package.json
  server/app.js
Labels: enhancement

#662 fix(): display buttons agent management
  client/app/telecom/telephony/alias/configuration/agents/ovhPabx/telecom-telephony-alias-configuration-agents-ovhPabx.html
Labels: bug, quality check ok

#644 fix(Line - Contact): Allow belgium siret in pattern
  client/app/telecom/telephony/service/contact/telecom-telephony-service-contact.html
Labels: bug, quality check ok

#666 feat(hubic): additionnal information on hubic voucher
  client/app/telecom/pack/slots/hubic/pack-hubic.controller.js
  client/app/telecom/pack/slots/hubic/pack-hubic.html
  client/app/telecom/pack/translations/Messages_fr_FR.xml
Labels: enhancement, quality check ok

#663 chore(): change target of anchor in bills section
  client/app/telecom/dashboard/bills/telecom-dashboard-bills.html
Labels: enhancement, quality check ok

#675 fix(xdsl): fix modem tab
  client/app/telecom/pack/xdsl/pack-xdsl.controller.js
Labels: bug

#648 fix(order alias): allow user country for international numbers
  client/app/telecom/telephony/billingAccount/orderAlias/telecom-telephony-billing-account-orderAlias.service.js
Labels: bug, quality check ok

#680 fix(xdsl): show/hide modem devices
  client/app/telecom/pack/xdsl/modem/connectedDevices/pack-xdsl-modem-connectedDevices.html
Labels: bug, quality check ok

#684 chore(bulk): re enable bulk action
  client/app/telecom/telephony/line/calls/simultaneousLines/telecom-telephony-line-calls-simultaneousLines.html
Labels: bulk action

#551 feat(atInternet): update tracking
  client/app/app.js
  client/app/telecom/dashboard/guides/telecom-dashboard-guides.controller.js
  client/app/telecom/dashboard/guides/telecom-dashboard-guides.html
  client/app/telecom/dashboard/telecom-dashboard.js
  client/app/telecom/sms/order/telecom-sms-order.controller.js
  client/app/telecom/telephony/alias/configuration/telecom-telephony-alias-configuration.controller.js
  client/app/telecom/telephony/billingAccount/orderAlias/telecom-telephony-billing-account-orderAlias.controller.js
  client/app/telecom/telephony/fax/telecom-telephony-fax.controller.js
  client/app/telecom/telephony/line/phone/accessories/telecom-telephony-line-phone-accessories.controller.js
  client/components/sidebar/sidebar.config.js
Labels: enhancement, quality check ok

#687 fix(xdsl): use of synchro values in place of estimated rate
  client/app/telecom/pack/move/offer/pack-move-offer.html
  client/app/telecom/pack/move/translations/Messages_fr_FR.xml
Labels: bug, quality check ok

#686 fix(css -popover): set hidden overflow to back from translated div
  client/app/common/less/popover.less
Labels: bug, quality check ok

#634 feat(trunk): trunk rates pack management
  client/app/telecom/telephony/line/calls/simultaneousLines/translations/Messages_fr_FR.xml
  client/app/telecom/telephony/line/calls/simultaneousLines/trunk/telecom-telephony-line-trunk-calls-simultaneousLines.controller.js
  client/app/telecom/telephony/line/calls/simultaneousLines/trunk/telecom-telephony-line-trunk-calls-simultaneousLines.html
  client/app/telecom/telephony/line/calls/simultaneousLines/trunk/telecom-telephony-line-trunk-calls.simultaneousLines.js
Labels: enhancement, feature, quality check ok

#661 Feature/telephony group update form to new oui-form
  client/app/telecom/telephony/billingAccount/administration/optionsGroup/telecom-telephony-billing-account-administration-options-group.controller.js
  client/app/telecom/telephony/billingAccount/administration/optionsGroup/telecom-telephony-billing-account-administration-options-group.html
  client/app/telecom/telephony/billingAccount/administration/optionsGroup/telecom-telephony-billing-account-administration-options-group.js
  client/app/telecom/telephony/billingAccount/administration/optionsGroup/translations/Messages_fr_FR.xml
  client/app/telecom/telephony/billingAccount/administration/telecom-telephony-billing-account-administration.controller.js
Labels: enhancement, quality check ok, translation required

#689 fix(me-alerts): fix bad links to billing statements
  client/components/me-alerts/me-alerts.config.js
  client/components/me-alerts/translations/Messages_fr_FR.xml
  package-lock.json
Labels: bug, quality check ok

#695 fix(pack): fix warning icon and text multiple lines to activate
  client/app/telecom/pack/slots/voipLine/activation/pack-voipLine-activation.html
Labels: bug, quality check ok

#688 fix(alias): add error message if menu cannot be deleted
  client/app/telecom/telephony/alias/configuration/ovhPabx/menus/telecom-telephony-alias-configuration-ovhPabx-menus.html
  client/components/telecom/telephony/group/number/feature/ovhPabx/menu/list/telephony-group-number-feature-ovh-pabx-menu-list.component.controller.js
Labels: bug, quality check ok

#691 fix(pack): fix select, dropdown menu and icons
  client/app/telecom/pack/slots/task/pack-task.controller.js
  client/app/telecom/pack/slots/task/pack-task.html
  client/app/telecom/telecom.less
Labels: bug, quality check ok

#694 Bugfix/empty wayname fix
  client/app/telecom/telephony/service/contact/telecom-telephony-service-contact.controller.js
Labels: bug, quality check ok

#690 fix(sms): resolve $title with implicit return
  client/app/telecom/sms/telecom-sms.js
Labels: bug

#696 fix(pack): fix display of gtr price pack migration
  client/app/telecom/pack/migration/offers/telecom-pack-migration-offers.html
Labels: bug, quality check ok

#692 fix(abbrev numbers): fix reload oui-datagrid component
  client/app/telecom/telephony/billingAccount/abbreviatedNumbers/telecom-telephony-abbreviatedNumbers.controller.js
  client/app/telecom/telephony/billingAccount/abbreviatedNumbers/telecom-telephony-abbreviatedNumbers.html
  client/app/telecom/telephony/line/calls/abbreviatedNumbers/telecom-telephony-line-calls-abbreviatedNumbers.controller.js
  client/app/telecom/telephony/line/calls/abbreviatedNumbers/telecom-telephony-line-calls-abbreviatedNumbers.html
  client/components/telecom/telephony/abbreviatedNumbers/telecom-telephony-abbreviated-numbers.component.js
  client/components/telecom/telephony/abbreviatedNumbers/telecom-telephony-abbreviated-numbers.html
Labels: bug, in progress, quality check ok

#702 fix(alias): allow plug and fax lines for member conf
  client/app/telecom/telephony/alias/configuration/members/oldPabx/telecom-telephony-alias-configuration-members-oldPabx.html
  client/components/telecom/telephony/alias/members/telecom-telephony-alias-members-add.html
  client/components/telecom/telephony/service/choice-popover/telecom-telephony-service-choice-popover.directive.controller.js
  client/components/telecom/telephony/service/choice-popover/translations/Messages_fr_FR.xml
Labels: bug, quality check ok

#674 Datagrid: add search and filter on abbreviated numbers
  client/components/telecom/telephony/abbreviatedNumbers/telecom-telephony-abbreviated-numbers.component.js
  client/components/telecom/telephony/abbreviatedNumbers/telecom-telephony-abbreviated-numbers.html
  client/components/telecom/telephony/abbreviatedNumbers/translations/Messages_fr_FR.xml
  server/routes.js
Labels: enhancement, quality check ok
