Repository ovh-ux/ovh-manager-telecom, pull requests merged in 2018-12, with the labels that each got.

#1144 fix(empty-array-and-address): fix empty array issue and change address
  client/app/telecom/telephony/line/management/terminate/telecom-telephony-line-management-terminate.html
  client/app/telecom/telephony/line/management/terminate/translations/Messages_fr_FR.xml
  client/app/telecom/telephony/line/phone/order/telecom-telephony-line-phone-order.html
  client/app/telecom/telephony/line/phone/order/translations/Messages_fr_FR.xml
  client/app/telecom/telephony/service/assist/orders/telecom-telephony-service-assist-orders.controller.js
Labels: bug, quality check ok, translation required

#1160 fix(deps): upgrade telecom-universe-components to v1.1.0
  package.json
  yarn.lock
Labels: bug

#1164 fix(internet): removal of deprecated links
  client/components/sidebar/sidebar.config.js
Labels: bug, quality check ok

#1166 fix(pack.resilisation): retrieve template from cache
  client/app/telecom/pack/resiliation/pack-resiliation.controller.js
  package.json
  yarn.lock
Labels: bug, quality check ok

#1165 refactor(eslintignore): remove old path
  .eslintignore
Labels: enhancement

#1173 fix(default-voicemail): use the correct filter name for format number
  client/app/telecom/telephony/service/voicemail/default/telecom-telephony-service-voicemail-default.controller.js
Labels: bug, quality check ok

#1174 fix(telephony): fix responsive popover placement and number details
  client/app/common/translations/Messages_fr_FR.xml
  client/components/telecom/telephony/timeCondition/slot/edit/telephony-time-condition-slot-edit.html
Labels: bug, quality check ok

#1178 fix(telephony.alias): remove ccs validate state change and delete popup
  client/app/telecom/telephony/alias/configuration/feature/contactCenterSolution/telecom-telephony-alias-configuration-contactCenterSolution.controller.js
  client/app/telecom/telephony/alias/configuration/feature/contactCenterSolution/timeCondition/telecom-telephony-alias-configuration-time-condition-easy-hunting.controller.js
Labels: bug, quality check ok

#1180 fix(voip-codecs): remove the test on line.phone to disable codecs button
  client/app/telecom/telephony/line/phone/telecom-telephony-line-phone.controller.js
Labels: bug, quality check ok

#1185 fix(telephony.alias): fix expert broken states and redirect button
  client/app/telecom/telephony/alias/configuration/feature/redirect/telecom-telephony-alias-configuration-redirect.html
  client/app/telecom/telephony/alias/configuration/records/ovhPabx/telecom-telephony-alias-configuration-records-ovhPabx.js
  client/app/telecom/telephony/alias/configuration/records/ovhPabx/translations/Messages_fr_FR.xml
  client/app/telecom/telephony/alias/configuration/scheduler/ovhPabx/telecom-telephony-alias-configuration-scheduler-ovh-pabx.js
  client/app/telecom/telephony/alias/configuration/scheduler/ovhPabx/translations/Messages_fr_FR.xml
  client/app/telecom/telephony/alias/configuration/telecom-telephony-alias-configuration.controller.js
  client/app/telecom/telephony/alias/translations/Messages_fr_FR.xml
Labels: bug, quality check ok

#1192 fix(telecom): upgrage ui-kit to fix broken select
  yarn.lock
Labels: bug, quality check

#1196 fix(telephony.alias): fix international numbers
  client/app/telecom/telephony/alias/configuration/feature/contactCenterSolution/lines/add/telecom-telephony-alias-configuration-lines-add.html
Labels: bug, quality check ok

#1197 fix(telephony.alias): allow fax numbers for redirect
  client/app/telecom/telephony/alias/configuration/feature/redirect/telecom-telephony-alias-configuration-redirect.controller.js
  client/app/telecom/telephony/alias/configuration/feature/redirect/telecom-telephony-alias-configuration-redirect.html
Labels: bug, quality check ok

#1205 fix(telephony.alias): fix expert menu modal actions choice
  client/components/telecom/telephony/group/number/feature/ovhPabx/menu/entry/edit/telephony-group-number-feature-ovh-pabx-menu-entry-edit.html
Labels: bug, quality check ok

#1202 fix(telephony.alias): set default line timeout to 20 sec
  client/app/telecom/telephony/alias/configuration/feature/contactCenterSolution/lines/add/telecom-telephony-alias-configuration-lines-add.controller.js
Labels: bug, quality check ok

#1203 fix(telephony.alias): undo deletion of used folder
  client/components/telecom/telephony/alias/members/telecom-telephony-alias-members-add-modal.component.js
  client/components/telecom/telephony/alias/members/telecom-telephony-alias-members-add-modal.html
  client/components/telecom/telephony/alias/members/telecom-telephony-alias-members-add.component.js
  client/components/telecom/telephony/alias/members/telecom-telephony-alias-members-add.html
  client/components/telecom/telephony/alias/members/telecom-telephony-alias-members.component.js
  client/components/telecom/telephony/alias/members/telecom-telephony-alias-members.html
  client/components/telecom/telephony/alias/members/telecom-telephony-alias-members.less
  client/components/telecom/telephony/alias/members/translations/Messages_cs_CZ.xml
  client/components/telecom/telephony/alias/members/translations/Messages_de_DE.xml
  client/components/telecom/telephony/alias/members/translations/Messages_en_ASIA.xml
  client/components/telecom/telephony/alias/members/translations/Messages_en_AU.xml
  client/components/telecom/telephony/alias/members/translations/Messages_en_CA.xml
  client/components/telecom/telephony/alias/members/translations/Messages_en_GB.xml
  client/components/telecom/telephony/alias/members/translations/Messages_en_SG.xml
  client/components/telecom/telephony/alias/members/translations/Messages_en_US.xml
  client/components/telecom/telephony/alias/members/translations/Messages_es_ES.xml
  client/components/telecom/telephony/alias/members/translations/Messages_es_US.xml
  client/components/telecom/telephony/alias/members/translations/Messages_fi_FI.xml
  client/components/telecom/telephony/alias/members/translations/Messages_fr_CA.xml
  client/components/telecom/telephony/alias/members/translations/Messages_fr_FR.xml
  client/components/telecom/telephony/alias/members/translations/Messages_it_IT.xml
  client/components/telecom/telephony/alias/members/translations/Messages_lt_LT.xml
  client/components/telecom/telephony/alias/members/translations/Messages_nl_NL.xml
  client/components/telecom/telephony/alias/members/translations/Messages_pl_PL.xml
  client/components/telecom/telephony/alias/members/translations/Messages_pt_PT.xml
Labels: bug, quality check ok

#1195 fix(telephony.alias): fix display of time condition slots
  client/app/telecom/telephony/alias/configuration/feature/contactCenterSolution/timeCondition/telecom-telephony-alias-configuration-time-condition.html
  client/components/telecom/telephony/timeCondition/slot/telephony-time-condition-slot.html
Labels: bug, quality check ok

#1198 fix(telephony.alias): remove mandatory options for sounds
  client/app/telecom/telephony/alias/configuration/feature/contactCenterSolution/sounds/telecom-telephony-alias-configuration-sounds.controller.js
  client/app/telecom/telephony/alias/configuration/feature/contactCenterSolution/sounds/telecom-telephony-alias-configuration-sounds.html
Labels: bug, quality check ok

#1207 fix(telephony.alias): remove conference pin code restrictions
  client/app/telecom/telephony/alias/configuration/feature/conference/telecom-telephony-alias-configuration-conference.html
Labels: bug, quality check ok

#1201 fix(labels-scheduler): translation for non translated labels
  client/components/telecom/telephony/scheduler/telephony-scheduler.html
  client/components/telecom/telephony/scheduler/translations/Messages_fr_FR.xml
Labels: bug, quality check ok, translation required

#1204 fix(telephony.alias): fix typo of closure overflow sounds
  client/app/telecom/telephony/alias/configuration/feature/contactCenterSolution/sounds/telecom-telephony-alias-configuration-sounds.html
  client/app/telecom/telephony/alias/configuration/feature/contactCenterSolution/sounds/translations/Messages_fr_FR.xml
Labels: bug, quality check ok, translation required

#1199 Remove some assistance menu items for FR
  client/app/common/translations/Messages_fr_FR.xml
  client/components/navbar/navbar.service.js
Labels: bug, quality check ok, translation required

#1209 fix(telephony.alias): rename state to prevent highlighting wrong menu
  client/app/telecom/telephony/alias/changeType/confirm/telecom-telephony-alias-changeType-confirm.controller.js
  client/app/telecom/telephony/alias/changeType/confirm/telecom-telephony-alias-changeType-confirm.html
  client/app/telecom/telephony/alias/changeType/telecom-telephony-alias-changeType.controller.js
  client/app/telecom/telephony/alias/changeType/telecom-telephony-alias-changeType.html
  client/app/telecom/telephony/alias/changeType/telecom-telephony-alias-changeType.js
  client/app/telecom/telephony/alias/changeType/translations/Messages_cs_CZ.xml
  client/app/telecom/telephony/alias/changeType/translations/Messages_de_DE.xml
  client/app/telecom/telephony/alias/changeType/translations/Messages_en_ASIA.xml
  client/app/telecom/telephony/alias/changeType/translations/Messages_en_AU.xml
  client/app/telecom/telephony/alias/changeType/translations/Messages_en_CA.xml
  client/app/telecom/telephony/alias/changeType/translations/Messages_en_GB.xml
  client/app/telecom/telephony/alias/changeType/translations/Messages_en_SG.xml
  client/app/telecom/telephony/alias/changeType/translations/Messages_en_US.xml
  client/app/telecom/telephony/alias/changeType/translations/Messages_es_ES.xml
  client/app/telecom/telephony/alias/changeType/translations/Messages_es_US.xml
  client/app/telecom/telephony/alias/changeType/translations/Messages_fi_FI.xml
  client/app/telecom/telephony/alias/changeType/translations/Messages_fr_CA.xml
  client/app/telecom/telephony/alias/changeType/translations/Messages_fr_FR.xml
  client/app/telecom/telephony/alias/changeType/translations/Messages_it_IT.xml
  client/app/telecom/telephony/alias/changeType/translations/Messages_lt_LT.xml
  client/app/telecom/telephony/alias/changeType/translations/Messages_nl_NL.xml
  client/app/telecom/telephony/alias/changeType/translations/Messages_pl_PL.xml
  client/app/telecom/telephony/alias/changeType/translations/Messages_pt_PT.xml
  client/app/telecom/telephony/alias/configuration/changeType/telecom-telephony-alias-configuration-changeType.js
  client/app/telecom/telephony/alias/telecom-telephony-alias-main.view.html
Labels: bug, quality check ok

#1213 fix(sms): fix long overflowing text on modal
  client/app/telecom/sms/sms/templates/remove/telecom-sms-sms-templates-remove.html
  client/app/telecom/sms/sms/templates/telecom-sms-sms-templates.controller.js
Labels: bug, quality check ok
