Repository ovh-ux/ovh-manager-telecom, pull requests merged in 2019-03, with the labels that each got.

#1306 fix(telecom.pack.slots.task): add missing translations
  client/app/telecom/pack/pack.js
  client/app/telecom/pack/slots/task/pack-task.html
  client/app/telecom/pack/slots/task/translations/Messages_cs_CZ.xml
  client/app/telecom/pack/slots/task/translations/Messages_de_DE.xml
  client/app/telecom/pack/slots/task/translations/Messages_en_ASIA.xml
  client/app/telecom/pack/slots/task/translations/Messages_en_AU.xml
  client/app/telecom/pack/slots/task/translations/Messages_en_CA.xml
  client/app/telecom/pack/slots/task/translations/Messages_en_GB.xml
  client/app/telecom/pack/slots/task/translations/Messages_en_SG.xml
  client/app/telecom/pack/slots/task/translations/Messages_en_US.xml
  client/app/telecom/pack/slots/task/translations/Messages_es_ES.xml
  client/app/telecom/pack/slots/task/translations/Messages_es_US.xml
  client/app/telecom/pack/slots/task/translations/Messages_fi_FI.xml
  client/app/telecom/pack/slots/task/translations/Messages_fr_CA.xml
  client/app/telecom/pack/slots/task/translations/Messages_fr_FR.xml
  client/app/telecom/pack/slots/task/translations/Messages_it_IT.xml
  client/app/telecom/pack/slots/task/translations/Messages_lt_LT.xml
  client/app/telecom/pack/slots/task/translations/Messages_nl_NL.xml
  client/app/telecom/pack/slots/task/translations/Messages_pl_PL.xml
  client/app/telecom/pack/slots/task/translations/Messages_pt_PT.xml
Labels: bug, quality check ok

#1305 refactor(telephony.alias): remove old custom class of oui-header-tabs
  client/app/telecom/telephony/alias/telecom-telephony-alias-main.view.html
Labels: enhancement, quality check ok

#1303 fix(telephony.alias): fix call forwarding option
  client/app/telecom/telephony/alias/configuration/feature/contactCenterSolution/lines/telecom-telephony-alias-configuration-lines.controller.js
  client/app/telecom/telephony/alias/configuration/feature/contactCenterSolution/lines/telecom-telephony-alias-configuration-lines.html
  package.json
  yarn.lock
Labels: bug, quality check ok

#1302 fix(telecom-termination): displaying warning icon twice
  client/app/telecom/telephony/fax/telecom-telephony-fax-main-view.html
  client/app/telecom/telephony/service/voicemail/options/telecom-telephony-service-voicemail-options.html
  client/app/telecom/telephony/service/voicemail/options/translations/Messages_fr_FR.xml
Labels: bug, quality check ok, translation required

#1304 fix(pack.xdsl.resiliation): use correct component binding
  client/app/telecom/pack/xdsl/resiliation/pack-xdsl-resiliation.html
  package.json
  yarn.lock
Labels: bug, quality check ok

#1314 fix: update key/label for call transfer
  client/app/telecom/telephony/line/phone/configuration/translations/Messages_fr_FR.xml
Labels: bug, quality check ok

#1300 fix: remove disable capabilities which generate error on refresh
  client/app/telecom/pack/xdsl/modem/connectedDevices/pack-xdsl-modem-connectedDevices.controller.js
Labels: bug, quality check ok

#1315 fix(fax.consumption): fix outgoing fax
  client/app/telecom/telephony/fax/consumption/outgoingFax/telecom-telephony-fax-consumption-outgoingFax.js
  client/app/telecom/telephony/line/consumption/telecom-telephony-line-consumption.js
  client/app/telecom/telephony/service/consumption/outgoingFax/telecom-telephony-service-consumption-outgoingFax.html
Labels: bug, quality check ok

#1316 fix(phone.config): fix config for yealink t46s
  client/app/telecom/telephony/line/phone/configuration/translations/Messages_fr_FR.xml
  client/app/telecom/telephony/line/phone/telecom-telephony-line-phone.constant.js
Labels: bug, quality check ok

#1319 fix(i18n): retrieve translations
  client/app/telecom/pack/slots/task/translations/Messages_cs_CZ.xml
  client/app/telecom/pack/slots/task/translations/Messages_de_DE.xml
  client/app/telecom/pack/slots/task/translations/Messages_en_ASIA.xml
  client/app/telecom/pack/slots/task/translations/Messages_en_AU.xml
  client/app/telecom/pack/slots/task/translations/Messages_en_CA.xml
  client/app/telecom/pack/slots/task/translations/Messages_en_GB.xml
  client/app/telecom/pack/slots/task/translations/Messages_en_SG.xml
  client/app/telecom/pack/slots/task/translations/Messages_en_US.xml
  client/app/telecom/pack/slots/task/translations/Messages_es_ES.xml
  client/app/telecom/pack/slots/task/translations/Messages_es_US.xml
  client/app/telecom/pack/slots/task/translations/Messages_fi_FI.xml
  client/app/telecom/pack/slots/task/translations/Messages_fr_CA.xml
  client/app/telecom/pack/slots/task/translations/Messages_it_IT.xml
  client/app/telecom/pack/slots/task/translations/Messages_lt_LT.xml
  client/app/telecom/pack/slots/task/translations/Messages_nl_NL.xml
  client/app/telecom/pack/slots/task/translations/Messages_pl_PL.xml
  client/app/telecom/pack/slots/task/translations/Messages_pt_PT.xml
  client/app/telecom/telephony/service/voicemail/options/translations/Messages_cs_CZ.xml
  client/app/telecom/telephony/service/voicemail/options/translations/Messages_de_DE.xml
  client/app/telecom/telephony/service/voicemail/options/translations/Messages_en_ASIA.xml
  client/app/telecom/telephony/service/voicemail/options/translations/Messages_en_AU.xml
  client/app/telecom/telephony/service/voicemail/options/translations/Messages_en_CA.xml
  client/app/telecom/telephony/service/voicemail/options/translations/Messages_en_GB.xml
  client/app/telecom/telephony/service/voicemail/options/translations/Messages_en_SG.xml
  client/app/telecom/telephony/service/voicemail/options/translations/Messages_en_US.xml
  client/app/telecom/telephony/service/voicemail/options/translations/Messages_es_ES.xml
  client/app/telecom/telephony/service/voicemail/options/translations/Messages_es_US.xml
  client/app/telecom/telephony/service/voicemail/options/translations/Messages_fi_FI.xml
  client/app/telecom/telephony/service/voicemail/options/translations/Messages_fr_CA.xml
  client/app/telecom/telephony/service/voicemail/options/translations/Messages_it_IT.xml
  client/app/telecom/telephony/service/voicemail/options/translations/Messages_lt_LT.xml
  client/app/telecom/telephony/service/voicemail/options/translations/Messages_nl_NL.xml
  client/app/telecom/telephony/service/voicemail/options/translations/Messages_pl_PL.xml
  client/app/telecom/telephony/service/voicemail/options/translations/Messages_pt_PT.xml
Labels: bug

#1318 build(deps): upgrade manager-* dependencies
  package.json
  yarn.lock
Labels: enhancement

#1322 build(deps): upgrade dependencies
  client/app/app.js
  client/app/index.js
  package.json
  yarn.lock
Labels: enhancement, one-manager, quality check ok

#1324 build(deps): upgrade ng-at-internet to v4.0.0
  client/app/app.js
  client/app/index.js
  package.json
  yarn.lock
Labels: enhancement, one-manager, quality check ok

#1327 fix(pack.sdsl.nav): hide modem tab for sdsl pack
  client/app/telecom/pack/xdsl/pack-xdsl.constant.js
  client/app/telecom/pack/xdsl/pack-xdsl.controller.js
Labels: bug, quality check ok

#1325 feat(config): update domain url
  client/app/config/all.js
Labels: enhancement, quality check ok
