Repository ovh-ux/ovh-manager-telecom, pull requests merged in 2019-02, with the labels that each got.

#1278 fix(pack): remove unnecessary toast error message of pack informations
  client/app/telecom/pack/pack.controller.js
Labels: bug, quality check ok

#1279 build(deps): upgrade ng-ovh-sso-auth and ng-ovh-sso-auth-modal-plugin
  client/app/app.js
  client/app/app.less
  client/app/index.js
  package.json
  yarn.lock
Labels: enhancement, quality check ok

#1214 fix(navbar): revamp style and texts
  client/app/app.less
  client/app/common/translations/Messages_fr_FR.xml
  client/components/navbar/navbar-builder.service.js
  client/components/navbar/navbar-menu-header/index.js
  client/components/navbar/navbar-menu-header/navbar-menu-header.component.html
  client/components/navbar/navbar-menu-header/navbar-menu-header.component.js
  client/components/navbar/navbar-menu-header/navbar-menu-header.html
  client/components/navbar/navbar-notification.service.js
  client/components/navbar/navbar.less
  client/components/navbar/navbar.service.js
  yarn.lock
Labels: bug, quality check ok, translation required

#1277 fix(telephony.alias): replace validate buttons by a footer bar
  client/app/telecom/telephony/alias/configuration/feature/contactCenterSolution/callsFiltering/telecom-telephony-alias-configuration-callsFiltering.controller.js
  client/app/telecom/telephony/alias/configuration/feature/contactCenterSolution/callsFiltering/telecom-telephony-alias-configuration-callsFiltering.html
  client/app/telecom/telephony/alias/configuration/feature/contactCenterSolution/callsFiltering/translations/Messages_fr_FR.xml
Labels: bug, quality check ok

#1274 fix: add upgrade offer status to display modem tab
  client/app/telecom/pack/xdsl/pack-xdsl.controller.js
  client/app/telecom/pack/xdsl/pack-xdsl.html
Labels: bug, quality check ok

#1253 feat(modem-change): add allow services change modem config
  client/app/telecom/pack/xdsl/modem/pack-xdsl-modem.html
  client/app/telecom/pack/xdsl/modem/pack-xdsl-modem.js
  client/app/telecom/pack/xdsl/modem/service/modal/pack-xdsl-modem-service-modal.controller.js
  client/app/telecom/pack/xdsl/modem/service/modal/pack-xdsl-modem-service-modal.html
  client/app/telecom/pack/xdsl/modem/service/pack-xdsl-modem-service.controller.js
  client/app/telecom/pack/xdsl/modem/service/pack-xdsl-modem-service.html
  client/app/telecom/pack/xdsl/modem/service/translations/Messages_fr_FR.xml
  yarn.lock
Labels: feature, quality check ok, translation required

#1286 fix: update from selected/unselected partial unbundling
  client/app/telecom/pack/move/pack-move.controller.js
Labels: bug, quality check ok

#1291 refactor(config): remove duplicate constant listTicket
  client/app/config/all.js
Labels: enhancement

#1280 fix(telephony.fax): use oui-datagrid search input
  client/app/telecom/telephony/service/consumption/incomingFax/telecom-telephony-service-consumption-incomingFax.html
Labels: bug, quality check ok

#1290 fix: display labels in phase with feature type
  client/components/telecom/telephony/group/number/feature/ovhPabx/telephony-group-number-feature-ovh-pabx.component.controller.js
Labels: bug, quality check ok

#1296 fix(deps): upgrade ng-ovh-telecom-universe-components to 2.0.2
  package.json
  yarn.lock
Labels: bug

#1301 fix(deps): upgrade ng-ovh-apiv7 to v2.0.0
  client/app/app.js
  client/app/app.less
  client/app/index.js
  package.json
  yarn.lock
Labels: bug, quality check ok
