Repository ovh-ux/ovh-manager-telecom, pull requests merged in 2019-01, with the labels that each got.

#1217 Upgrade stylelint
  client/app/app.less
  package.json
  yarn.lock
Labels: enhancement

#1220 build(eslint): use eslint-formatter-pretty
  package.json
  yarn.lock
Labels: enhancement

#1206 feat(telephony-guides): add guides tab for telephony
  client/app/telecom/telephony/billingAccount/guides/telecom-telephony-guides.controller.js
  client/app/telecom/telephony/billingAccount/guides/telecom-telephony-guides.html
  client/app/telecom/telephony/billingAccount/guides/telecom-telephony-guides.js
  client/app/telecom/telephony/billingAccount/guides/translations/Messages_fr_FR.xml
  client/app/telecom/telephony/billingAccount/telecom-telephony-billing-account.html
  client/app/telecom/telephony/billingAccount/translations/Messages_fr_FR.xml
  client/app/telecom/telephony/telecom-telephony.constant.js
Labels: feature, quality check ok, translation required

#1221 refactor(babel): remove unused configuration and dependencies
  .babelrc
  package.json
Labels: enhancement

#1215 fix(telephony.alias): remove pattern for lines to add
  client/app/telecom/telephony/alias/configuration/feature/contactCenterSolution/lines/add/telecom-telephony-alias-configuration-lines-add.html
Labels: bug, quality check ok

#1223 fix(telephony.alias): fix tuc component property name
  client/app/telecom/telephony/alias/telecom-telephony-alias-main.view.html
Labels: bug, quality check ok

#1227 build(deps): upgrade ng-tail-logs to v2.0.0-beta.0
  client/app/app.js
  client/app/app.less
  client/app/index.js
  client/app/telecom/overTheBox/logs/overTheBox-logs.controller.js
  client/app/telecom/overTheBox/logs/overTheBox-logs.html
  package.json
  yarn.lock
Labels: enhancement, one-manager, quality check ok

#1200 feat(bank-holidays): add week-end and bank holidays
  client/app/telecom/telephony/alias/portability/order/telecom-telephony-alias-portability-order.controller.js
  client/app/telecom/telephony/alias/portability/order/telecom-telephony-alias-portability-order.html
  client/app/telecom/telephony/telecom-telephony.constant.js
  client/components/telecom/telephony/scheduler/actions/bankHolidays/telephony-scheduler-bank-holidays.controller.js
Labels: feature, quality check ok

#1233 build(deps): upgrade ng-tail-logs to v2.0.0-beta.1
  package.json
  yarn.lock
Labels: bug

#1237 build(deps): upgrade ng-uirouter-title to v2.0.0-beta.3
  client/app/app.js
  client/app/index.js
  package.json
  yarn.lock
Labels: enhancement, one-manager, quality check ok

#1241 fix(pack): display empty services message correctly
  client/app/telecom/pack/pack.html
Labels: bug, quality check ok

#1242 fix(telephony.alias): fix change type state name
  client/app/telecom/telephony/alias/configuration/telecom-telephony-alias-configuration.controller.js
Labels: bug, quality check ok

#1228 feat(voip-line): remove useless modal
  client/app/telecom/telephony/alias/configuration/agents/ovhPabx/telecom-telephony-alias-configuration-agents-ovhPabx.controller.js
Labels: feature, quality check ok

#1243 fix(telephony.alias): fix description of added lines in queue
  client/app/telecom/telephony/alias/configuration/feature/contactCenterSolution/lines/add/telecom-telephony-alias-configuration-lines-add.controller.js
Labels: bug, quality check ok

#1250 fix(telephony.alias.dashboard): set right configuration state name
  client/app/telecom/telephony/alias/dashboard/telecom-telephony-alias-dashboard.controller.js
Labels: bug, quality check ok

#1236 build(deps): upgrade @ovh-ux/telecom-universe-components to 1.5.1
  package.json
  yarn.lock
Labels: enhancement

#1256 fix(overthebox.order): use url instead of state
  client/app/config/all.js
  client/components/sidebar/sidebar.config.js
Labels: bug

#1263 fix(sms): fix display of modal fields
  client/app/telecom/sms/sms/compose/addPhonebookContact/telecom-sms-sms-compose-addPhonebookContact.html
Labels: bug, quality check ok

#1262 feat: use translations for oui-clipboard
  client/app/app.js
  client/app/common/translations/Messages_fr_FR.xml
Labels: feature, quality check ok

#1269 fix(diagnostic): ask for modem MAC address
  package.json
  yarn.lock
Labels: bug, quality check ok

#1275 fix: avoid the portability if partial unbundling
  client/app/telecom/pack/move/pack-move.controller.js
  client/app/telecom/pack/move/pack-move.html
Labels: bug, quality check ok

#1264 feat(config-dhcp): add checking for denied dns ips
  client/app/telecom/pack/xdsl/modem/router/dhcp/pack-xdsl-modem-dhcp-modal.component.js
  client/app/telecom/pack/xdsl/modem/router/dhcp/pack-xdsl-modem-dhcp-modal.html
  client/app/telecom/pack/xdsl/modem/router/dhcp/pack-xdsl-modem-dhcp.controller.js
  client/app/telecom/pack/xdsl/modem/router/dhcp/pack-xdsl-modem-dhcp.factory.js
  client/app/telecom/pack/xdsl/modem/router/dhcp/translations/Messages_fr_FR.xml
Labels: feature, quality check ok, translation required

#1240 feat(order-sda): add order for redirections sda
  client/app/telecom/telephony/billingAccount/orderAlias/geographical/telecom-telephony-billing-account-orderAlias-geographical.controller.js
  client/app/telecom/telephony/billingAccount/orderAlias/geographical/telecom-telephony-billing-account-orderAlias-geographical.html
  client/app/telecom/telephony/billingAccount/orderAlias/geographical/translations/Messages_fr_FR.xml
  client/app/telecom/telephony/billingAccount/orderAlias/nonGeographical/telecom-telephony-billing-account-orderAlias-nonGeographical.controller.js
  client/app/telecom/telephony/billingAccount/orderAlias/nonGeographical/telecom-telephony-billing-account-orderAlias-nonGeographical.html
  client/app/telecom/telephony/billingAccount/orderAlias/nonGeographical/translations/Messages_fr_FR.xml
Labels: feature, quality check ok, translation required
