Repository ovh-ux/ovh-manager-telecom, pull requests merged in 2019-04, with the labels that each got.

#1331 feat(telephony.line.details): add web interface informations
  client/app/telecom/telephony/line/details/telecom-telephony-line-details.html
  client/app/telecom/telephony/line/details/translations/Messages_fr_FR.xml
Labels: feature, quality check ok, translation required

#1332 feat(telephony.service.contact): use address for updating contact
  client/app/telecom/telephony/service/contact/telecom-telephony-service-contact.html
Labels: feature, quality check ok

#1337 feat(telephony.line.details): display web informations only for yealink
  client/app/telecom/telephony/line/details/telecom-telephony-line-details.controller.js
  client/app/telecom/telephony/line/details/telecom-telephony-line-details.html
  client/app/telecom/telephony/line/details/translations/Messages_fr_FR.xml
Labels: feature, quality check ok

#1344 Update contributing
  CONTRIBUTING.md
Labels: enhancement

#1343 feat(telepony.line.calls): add tooltip on simultaneous lines
  client/app/telecom/telephony/line/calls/simultaneousLines/telecom-telephony-line-calls-simultaneousLines.html
  client/app/telecom/telephony/line/calls/simultaneousLines/translations/Messages_fr_FR.xml
Labels: quality check ok, translation required

#1350 feat(chatbot): open the chatbot from the assistance menu
  client/app/app.js
  client/app/common/translations/Messages_fr_FR.xml
  client/components/navbar/navbar.service.js
  client/index.html
  package.json
  yarn.lock
Labels: feature, quality check ok

#1355 build(deps): upgrade some dependencies
  package.json
  yarn.lock
Labels: enhancement

#1359 fix(i18n): retrieve translations
  client/app/common/translations/Messages_cs_CZ.xml
  client/app/common/translations/Messages_de_DE.xml
  client/app/common/translations/Messages_en_ASIA.xml
  client/app/common/translations/Messages_en_AU.xml
  client/app/common/translations/Messages_en_CA.xml
  client/app/common/translations/Messages_en_GB.xml
  client/app/common/translations/Messages_en_SG.xml
  client/app/common/translations/Messages_en_US.xml
  client/app/common/translations/Messages_es_ES.xml
  client/app/common/translations/Messages_es_US.xml
  client/app/common/translations/Messages_fi_FI.xml
  client/app/common/translations/Messages_fr_CA.xml
  client/app/common/translations/Messages_it_IT.xml
  client/app/common/translations/Messages_lt_LT.xml
  client/app/common/translations/Messages_nl_NL.xml
  client/app/common/translations/Messages_pl_PL.xml
  client/app/common/translations/Messages_pt_PT.xml
Labels: bug

#1352 fix(pack): switch package mondial relay to ng-ovh one with update
  client/app/app.js
  client/app/app.less
  client/app/index.js
  client/components/ovh-angular-mondial-relay/ovh-angular-mondial-relay.js
  package.json
  yarn.lock
Labels: bug, quality check ok

#1360 refactor: remove extra chatbot import from app.less file
  client/app/app.less
Labels: enhancement

#1362 fix(components.navbar): remove duplicate ticket entry
  client/app/common/translations/Messages_fr_FR.xml
  client/components/navbar/navbar.service.js
Labels: bug, quality check ok

#1365 fix(pack.line.activation): use new mondial relay element
  client/app/telecom/pack/slots/voipLine/activation/pack-voipLine-activation.html
Labels: bug, quality check ok

#1370 feat(telephony.line.management): migrate discover line to alias
  client/app/telecom/telephony/line/management/telecom-telephony-line-management.controller.js
Labels: feature, quality check ok
