Repository ovh-ux/ovh-manager-telecom, pull requests merged in 2019-08, with the labels that each got.

#1468 build(deps): upgrade some dependencies
  package.json
  yarn.lock
Labels: dependencies

#1470 fix(telephony.alias.members): move initialization in $onInit
  client/components/telecom/telephony/alias/members/telecom-telephony-alias-members.component.js
Labels: bug

#1469 Release v10.31.3
  client/app/telecom/orders/accessories/translations/Messages_it_IT.json
  client/app/telecom/orders/accessories/translations/Messages_pt_PT.json
  client/app/telecom/pack/xdsl/access/translations/Messages_es_ES.json
  client/app/telecom/pack/xdsl/access/translations/Messages_pt_PT.json
  client/app/telecom/telephony/line/calls/forward/telecom-telephony-line-calls-forward.controller.js
  client/app/telecom/telephony/line/calls/forward/telecom-telephony-line-calls-forward.html
  client/app/telecom/telephony/line/calls/forward/translations/Messages_fr_FR.json
  package.json
  yarn.lock
Labels: release :package:

#1473 fix(components.sidebar): add missing translations for en_* files
  client/components/sidebar/translations/Messages_en_CA.json
  client/components/sidebar/translations/Messages_en_GB.json
  client/components/sidebar/translations/Messages_en_US.json
Labels: bug

#1478 feat: add @ovh-ux/ng-ui-router-line-progress
  client/app/app.js
  client/app/app.less
  client/index.html
  package.json
  yarn.lock
Labels: feature

#1480 fix: update manager urls
  client/app/config/all.js
Labels: bug

#1484 feat: add @ovh-ux/ng-ovh-request-tagger
  package.json
  yarn.lock
Labels: enhancement

#1485 build(deps): upgrade some dependencies
  package.json
  yarn.lock
Labels: dependencies

#1482 refactor: remove deprecated ovh-angular-input-number-spinner dependency
  client/app/app.js
  client/app/index.js
  client/app/telecom/telephony/line/phone/configuration/telecom-telephony-line-phone-configuration.less
  client/components/telecom/telephony/alias/members/telecom-telephony-alias-members.less
  package.json
  yarn.lock
Labels: enhancement

#1481 feat(xdsl.modem): add button to reconfigure voip line
  client/app/telecom/pack/xdsl/modem/reset/pack-xdsl-modem-reset.controller.js
  client/app/telecom/pack/xdsl/modem/reset/pack-xdsl-modem-reset.html
  client/app/telecom/pack/xdsl/modem/reset/translations/Messages_fr_FR.json
Labels: feature, quality check ok, translation required

#1487 fix(pack.slots): prevent include the missing no-element partial
  client/app/telecom/pack/slots/domain/pack-domain.html
  client/app/telecom/pack/slots/exchangeAccount/pack-exchangeAccount.html
  client/app/telecom/pack/slots/exchangeIndividual/pack-exchangeIndividual.html
  client/app/telecom/pack/slots/exchangeLite/pack-exchangeLite.html
  client/app/telecom/pack/slots/hostedEmail/pack-hostedEmail.html
  client/app/telecom/pack/slots/voipBillingAccount/pack-voipBillingAccount.html
  client/app/telecom/pack/slots/voipEcoFax/pack-voipEcoFax.html
  client/app/telecom/pack/slots/xdslAccess/pack-xdslAccess.html
Labels: bug

#1486 Release v10.33.0
  client/app/app.js
  client/app/index.js
  client/app/telecom/pack/xdsl/modem/reset/pack-xdsl-modem-reset.controller.js
  client/app/telecom/pack/xdsl/modem/reset/pack-xdsl-modem-reset.html
  client/app/telecom/pack/xdsl/modem/reset/translations/Messages_fr_FR.json
  client/app/telecom/telephony/line/phone/configuration/telecom-telephony-line-phone-configuration.less
  client/components/telecom/telephony/alias/members/telecom-telephony-alias-members.less
  package.json
  yarn.lock
Labels: release :package:

#1494 build(deps): upgrade ng-ovh-sso-auth to v4.2.0
  package.json
  yarn.lock
Labels: dependencies

#1495 docs: remove CODE_OF_CONDUCT.md file.
  CODE_OF_CONDUCT.md
Labels: documentation

#1497 Release v10.33.1
  client/app/telecom/orders/accessories/translations/Messages_es_ES.json
  client/app/telecom/pack/xdsl/modem/reset/translations/Messages_es_ES.json
  client/app/telecom/pack/xdsl/modem/reset/translations/Messages_fr_CA.json
  client/app/telecom/pack/xdsl/modem/reset/translations/Messages_it_IT.json
  client/app/telecom/pack/xdsl/modem/reset/translations/Messages_pl_PL.json
  package.json
  yarn.lock
Labels: release :package:

#1500 build(package.json): bump ng-ovh-sso-auth to v4.2.1
  package.json
  yarn.lock
Labels: dependencies

#1493 fix(telephony.alias): remove api error detail message
  client/components/telecom/telephony/group/number/feature/ovhPabx/menu/telephony-group-number-feature-ovh-pabx-menu.component.controller.js
Labels: bug, quality check ok

#1503 Release v10.33.3
  client/components/telecom/telephony/group/number/feature/ovhPabx/menu/telephony-group-number-feature-ovh-pabx-menu.component.controller.js
Labels: release :package:
