Repository ovh-ux/ovh-manager-telecom, pull requests merged in 2019-09, with the labels that each got.

#1514 feat: add manager banner
  package.json
  yarn.lock
Labels: quality check ok

#1512 fix(telephony.phone): fix order of function keys
  client/app/telecom/telephony/line/phone/programmableKeys/telecom-telephony-line-phone-programmableKeys.controller.js
Labels: bug, quality check ok

#1513 fix(xdsl): fix enabling of sip alg option
  client/app/telecom/pack/xdsl/modem/service/pack-xdsl-modem-service.controller.js
Labels: bug, quality check ok

#1518 fix(telephony.reboot): reboot disabled only for gigaset and spa112
  client/app/telecom/telephony/line/phone/reboot/telecom-telephony-line-phone-reboot.controller.js
Labels: bug, quality check ok

#1520 Release v10.35.1
  client/app/telecom/pack/xdsl/modem/service/pack-xdsl-modem-service.controller.js
  client/app/telecom/telephony/line/phone/programmableKeys/telecom-telephony-line-phone-programmableKeys.controller.js
  client/app/telecom/telephony/line/phone/reboot/telecom-telephony-line-phone-reboot.controller.js
Labels: release :package:
