Repository ovh-ux/ovh-manager-telecom, pull requests merged in 2019-05, with the labels that each got.

#1376 fix(telephony.alias.ccs.queues): set correct type of queue member
  client/components/telecom/telephony/alias/members/telecom-telephony-alias-members.html
  client/components/telecom/telephony/alias/members/translations/Messages_fr_FR.xml
Labels: bug, quality check ok, translation required

#1375 fix(line.phone.accessories): replace input number by oui numeric
  client/app/telecom/telephony/line/phone/accessories/choice/telecom-telephony-line-phone-accessories-choice.html
Labels: bug, quality check ok

#1371 fix(telephony.order): fix property alias to display found options
  client/app/telecom/telephony/billingAccount/orderAlias/geographical/telecom-telephony-billing-account-orderAlias-geographical.html
Labels: bug, quality check ok

#1381 fix(deps): upgrade ng-ovh-telecom-universe-components to v3.0.3
  package.json
  yarn.lock
Labels: bug, quality check, quality check ok

#1351 feat(xdsl.modem.templates): add config for modem template
  client/app/telecom/pack/xdsl/modem/pack-xdsl-modem.html
  client/app/telecom/pack/xdsl/modem/pack-xdsl-modem.js
  client/app/telecom/pack/xdsl/modem/templates/config/modal/pack-xdsl-modem-template-config-modal.controller.js
  client/app/telecom/pack/xdsl/modem/templates/config/modal/pack-xdsl-modem-template-config-modal.html
  client/app/telecom/pack/xdsl/modem/templates/config/pack-xdsl-modem-templates-config.controller.js
  client/app/telecom/pack/xdsl/modem/templates/config/pack-xdsl-modem-templates-config.html
  client/app/telecom/pack/xdsl/modem/templates/config/pack-xdsl-modem-templates-config.js
  client/app/telecom/pack/xdsl/modem/templates/config/translations/Messages_fr_FR.xml
  client/app/telecom/pack/xdsl/modem/templates/pack-xdsl-modem-templates.component.js
  client/app/telecom/pack/xdsl/modem/templates/pack-xdsl-modem-templates.controller.js
  client/app/telecom/pack/xdsl/modem/templates/pack-xdsl-modem-templates.html
  client/app/telecom/pack/xdsl/modem/templates/translations/Messages_fr_FR.xml
  client/app/telecom/pack/xdsl/pack-xdsl.controller.js
  yarn.lock
Labels: feature, quality check ok, translation required

#1382 feat(xdsl.access.ipv6): update ipv6 set on or set off message
  client/app/telecom/pack/xdsl/access/ipv6/pack-xdsl-access-ipv6.controller.js
  client/app/telecom/pack/xdsl/access/ipv6/translations/Messages_fr_FR.xml
Labels: bug, quality check ok, translation required

#1394 build: remove yarn-error.log file
  yarn-error.log
Labels: enhancement

#1383 fix(deps): upgrade some dependencies
  client/app/app.js
  package.json
  yarn.lock
Labels: bug
