Repository ovh-ux/ovh-manager-telecom, pull requests merged in 2019-07, with the labels that each got.

#1430 fix(line.management): display mgcp ip restriction page
  client/app/telecom/telephony/line/management/mgcpIpRestriction/telecom-telephony-line-mgcpIpRestriction.controller.js
  client/app/telecom/telephony/line/management/mgcpIpRestriction/translations/Messages_fr_FR.json
Labels: bug, quality check ok

#1433 Release v10.28.2
  client/app/telecom/pack/xdsl/modem/templates/translations/Messages_en_ASIA.json
  client/app/telecom/pack/xdsl/modem/templates/translations/Messages_en_AU.json
  client/app/telecom/pack/xdsl/modem/templates/translations/Messages_en_CA.json
  client/app/telecom/pack/xdsl/modem/templates/translations/Messages_en_GB.json
  client/app/telecom/pack/xdsl/modem/templates/translations/Messages_en_SG.json
  client/app/telecom/pack/xdsl/modem/templates/translations/Messages_en_US.json
  client/app/telecom/pack/xdsl/modem/templates/translations/Messages_fi_FI.json
  client/app/telecom/pack/xdsl/modem/templates/translations/Messages_lt_LT.json
  client/app/telecom/telephony/line/management/mgcpIpRestriction/telecom-telephony-line-mgcpIpRestriction.controller.js
  client/app/telecom/telephony/line/management/mgcpIpRestriction/translations/Messages_fr_FR.json
Labels: release :package:

#1432 feat(telephony.linesgroup): add voice fax lines to group lines
  client/app/telecom/telephony/billingAccount/administration/linesGroup/telecom-telephony-billing-account-administration-lines-group.controller.js
Labels: feature, quality check ok

#1437 Release v10.29.0
  client/app/telecom/telephony/billingAccount/administration/linesGroup/telecom-telephony-billing-account-administration-lines-group.controller.js
  client/app/telecom/telephony/line/management/mgcpIpRestriction/translations/Messages_it_IT.json
Labels: release :package:

#1441 build(deps): upgrade ovh-api-services to v7.0.0
  package.json
  yarn.lock
Labels: dependencies

#1436 feat(telephony.contact): update synchronization message for directory
  client/app/telecom/telephony/service/contact/telecom-telephony-service-contact.constants.js
  client/app/telecom/telephony/service/contact/telecom-telephony-service-contact.controller.js
  client/app/telecom/telephony/service/contact/telecom-telephony-service-contact.html
  client/app/telecom/telephony/service/contact/translations/Messages_fr_FR.json
Labels: bug, quality check ok, translation required

#1442 Release v10.30.0
  client/app/telecom/telephony/line/management/mgcpIpRestriction/translations/Messages_en_ASIA.json
  client/app/telecom/telephony/line/management/mgcpIpRestriction/translations/Messages_en_AU.json
  client/app/telecom/telephony/line/management/mgcpIpRestriction/translations/Messages_en_CA.json
  client/app/telecom/telephony/line/management/mgcpIpRestriction/translations/Messages_en_GB.json
  client/app/telecom/telephony/line/management/mgcpIpRestriction/translations/Messages_en_SG.json
  client/app/telecom/telephony/line/management/mgcpIpRestriction/translations/Messages_en_US.json
  client/app/telecom/telephony/line/management/mgcpIpRestriction/translations/Messages_fi_FI.json
  client/app/telecom/telephony/line/management/mgcpIpRestriction/translations/Messages_lt_LT.json
  client/app/telecom/telephony/service/contact/telecom-telephony-service-contact.constants.js
  client/app/telecom/telephony/service/contact/telecom-telephony-service-contact.controller.js
  client/app/telecom/telephony/service/contact/telecom-telephony-service-contact.html
  client/app/telecom/telephony/service/contact/translations/Messages_fr_FR.json
  package.json
  yarn.lock
Labels: release :package:

#1445 build: bump @ovh-ux/ng-ovh-checkbox-table
  client/app/app.js
  client/app/index.js
  package.json
  yarn.lock
Labels: dependencies

#1440 build: bump angular to ^1.7.5
  client/app/app.js
  client/app/telecom/pack/migration/offers/telecom-pack-migration-offers.controller.js
  client/app/telecom/pack/migration/offers/telecom-pack-migration-offers.html
  client/app/telecom/pack/move/address/future/pack-move-address-future.html
  client/app/telecom/pack/slots/emailPro/detail/pack-emailPro-detail.controller.js
  client/app/telecom/pack/slots/emailPro/detail/pack-emailPro-detail.html
  client/app/telecom/pack/slots/hostedEmail/detail/pack-hostedEmail-detail.html
  client/app/telecom/telephony/alias/configuration/feature/contactCenterSolution/lines/add/telecom-telephony-alias-configuration-lines-add.html
  client/app/telecom/telephony/alias/configuration/mode/easyPabx/telecom-telephony-alias-configuration-mode-easyPabx.html
  client/app/telecom/telephony/alias/configuration/mode/miniPabx/telecom-telephony-alias-configuration-mode-miniPabx.html
  client/app/telecom/telephony/alias/configuration/queues/ovhPabx/telecom-telephony-alias-configuration-queues-ovhPabx.html
  client/app/telecom/telephony/billingAccount/billing/depositMovement/telecom-telephony-billing-account-billing-deposit-movement.html
  client/app/telecom/telephony/billingAccount/manageContacts/telecom-telephony-billing-account-manageContacts.less
  client/app/telecom/telephony/line/calls/forward/telecom-telephony-line-calls-forward.html
  client/components/telecom/telephony/alias/members/telecom-telephony-alias-members-add.html
  client/components/telecom/telephony/alias/members/telecom-telephony-alias-members.html
  client/components/telecom/telephony/group/line/phone/configration/extension/line-phone-configuration-extension.html
  client/components/telecom/telephony/group/line/phone/configration/line-phone-configuration.html
  client/components/telecom/telephony/group/number/feature/conference/partiticipant/telephony-group-number-feature-conference-participant-actions.html
  client/components/telecom/telephony/group/number/feature/ovhPabx/dialplan/edit/telephony-group-number-feature-ovh-pabx-dialplan-edit.html
  client/components/telecom/telephony/group/number/feature/ovhPabx/dialplan/extension/rule/edit/telephony-group-number-feature-ovh-pabx-dialplan-extension-rule-edit.html
  client/components/telecom/telephony/service/time-condition-configuration/telecom-telephony-service-time-condition-configuration.service.js
  package.json
  yarn.lock
Labels: dependencies, quality check ok

#1446 Fix/telephony bulk phone keynum
  client/app/telecom/telephony/line/phone/programmableKeys/telecom-telephony-line-phone-programmableKeys.controller.js
  client/app/telecom/telephony/line/phone/programmableKeys/telecom-telephony-line-phone-programmableKeys.html
Labels: bug, quality check ok

#1449 build(deps): upgrade some dependencies
  package.json
  yarn.lock
Labels: dependencies

#1450 Release v10.31.0
  client/app/app.js
  client/app/index.js
  client/app/telecom/telephony/line/management/mgcpIpRestriction/translations/Messages_es_ES.json
  client/app/telecom/telephony/line/phone/programmableKeys/telecom-telephony-line-phone-programmableKeys.controller.js
  client/app/telecom/telephony/line/phone/programmableKeys/telecom-telephony-line-phone-programmableKeys.html
  client/app/telecom/telephony/service/contact/translations/Messages_en_ASIA.json
  client/app/telecom/telephony/service/contact/translations/Messages_en_AU.json
  client/app/telecom/telephony/service/contact/translations/Messages_en_CA.json
  client/app/telecom/telephony/service/contact/translations/Messages_en_GB.json
  client/app/telecom/telephony/service/contact/translations/Messages_en_SG.json
  client/app/telecom/telephony/service/contact/translations/Messages_en_US.json
  client/app/telecom/telephony/service/contact/translations/Messages_fi_FI.json
  client/app/telecom/telephony/service/contact/translations/Messages_lt_LT.json
  package.json
  yarn.lock
Labels: release :package:

#1447 fix(pack.xdsl.translations): add forgotten ids
  client/app/telecom/pack/xdsl/access/translations/Messages_fr_FR.json
Labels: bug, translation required

#1455 fix(telephony.consumption.pie.chart): fill with default empty color
  client/components/telecom/telephony/group/consumption/pie-chart/telephony-group-consumption-pie-chart.less
Labels: bug, quality check ok

#1454 fix(pack.move.offer): loading offer on init function
  client/app/telecom/pack/move/offer/pack-move-offer.component.js
Labels: bug, quality check ok

#1459 Release v10.31.2
  client/app/telecom/pack/move/offer/pack-move-offer.component.js
  client/app/telecom/pack/xdsl/access/translations/Messages_fr_FR.json
  client/app/telecom/telephony/service/contact/translations/Messages_es_ES.json
  client/app/telecom/telephony/service/contact/translations/Messages_it_IT.json
Labels: release :package:

#1462 build(deps): upgrade ovh-api-services to v8.0.0
  package.json
  yarn.lock
Labels: dependencies

#1464 build(deps): upgrade ng-ovh-http to v4.0.2
  package.json
  yarn.lock
Labels: dependencies

#1463 fix(pack.migration.building-details): manage empty list for stairs
  client/app/telecom/pack/migration/building-details/telecom-pack-migration-building-details.controller.js
Labels: bug, quality check ok

#1465 Release v10.31.3
  client/app/telecom/pack/migration/building-details/telecom-pack-migration-building-details.controller.js
  client/app/telecom/pack/xdsl/access/translations/Messages_it_IT.json
  package.json
  yarn.lock
Labels: release :package:

#1458 line calls forward list improvements
  client/app/telecom/telephony/line/calls/forward/telecom-telephony-line-calls-forward.controller.js
  client/app/telecom/telephony/line/calls/forward/telecom-telephony-line-calls-forward.html
  client/app/telecom/telephony/line/calls/forward/translations/Messages_fr_FR.json
Labels: bug, good first issue, quality check ok
