Repository ovh-ux/ovh-manager-telecom, pull requests merged in 2019-06, with the labels that each got.

#1403 fix(deps): upgrade some dependencies
  package.json
  yarn.lock
Labels: bug

#1415 fix(translations): update providers to use json format
  client/app/telecom/orders/sms/telecom-orders-sms.js
  client/app/telecom/pack/pack.js
  client/app/telecom/pack/xdsl/modem/pack-xdsl-modem.js
  client/app/telecom/pack/xdsl/pack-xdsl.js
  client/app/telecom/telephony/fax/consumption/incomingFax/telecom-telephony-fax-consumption-incomingFax.js
  client/app/telecom/telephony/fax/consumption/outgoingFax/telecom-telephony-fax-consumption-outgoingFax.js
  client/app/telecom/telephony/line/consumption/telecom-telephony-line-consumption.js
  client/app/telecom/telephony/line/telecom-telephony-line.js
Labels: bug, quality check

#1413 feat(phone.config): add new parameter value for yealink t46s
  client/app/telecom/telephony/line/phone/configuration/translations/Messages_fr_FR.json
Labels: bug, quality check ok

#1416 fix(deps): upgrade some dependencies
  package.json
  yarn.lock
Labels: bug

#1418 Release v10.27.1
  package.json
  yarn.lock
Labels: release :package:

#1421 fix(deps): upgrade ng-ovh-otrs to v7.1.4
  package.json
  yarn.lock
Labels: bug

#1422 build: bump @ovh-ux/manager-navbar
  client/app/app.js
  package.json
  yarn.lock
Labels: dependencies

#1414 feat(modem.template): display error message if name invalid
  client/app/telecom/pack/xdsl/modem/templates/pack-xdsl-modem-template.constant.js
  client/app/telecom/pack/xdsl/modem/templates/pack-xdsl-modem-templates.controller.js
  client/app/telecom/pack/xdsl/modem/templates/translations/Messages_fr_FR.json
Labels: feature, quality check ok

#1423 Release v10.28.0
  client/app/app.js
  client/app/telecom/pack/xdsl/modem/templates/pack-xdsl-modem-template.constant.js
  client/app/telecom/pack/xdsl/modem/templates/pack-xdsl-modem-templates.controller.js
  client/app/telecom/pack/xdsl/modem/templates/translations/Messages_fr_FR.json
  package.json
  yarn.lock
Labels: release :package:

#1426 fix(deps): upgrade some dependencies
  package.json
  yarn.lock
Labels: dependencies

#1427 Release v10.28.1
  client/app/telecom/telephony/line/phone/configuration/translations/Messages_en_ASIA.json
  client/app/telecom/telephony/line/phone/configuration/translations/Messages_en_AU.json
  client/app/telecom/telephony/line/phone/configuration/translations/Messages_en_CA.json
  client/app/telecom/telephony/line/phone/configuration/translations/Messages_en_GB.json
  client/app/telecom/telephony/line/phone/configuration/translations/Messages_en_SG.json
  client/app/telecom/telephony/line/phone/configuration/translations/Messages_en_US.json
  client/app/telecom/telephony/line/phone/configuration/translations/Messages_fi_FI.json
  client/app/telecom/telephony/line/phone/configuration/translations/Messages_lt_LT.json
  package.json
  yarn.lock
Labels: release :package:
